const fs = require('fs');
const path = require('path');

const list = [];

list.push(
  ['Red-Eyed Tree Frog', 'Agalychnis callidryas', 'Rainforest canopy acrobat with glowing ruby eyes', 'Vibrant green jumper that hides under broad leaves by day and flashes giant scarlet eyes to startle predators when surprised.', 'Rainforest canopies of Central America', 'Crickets, moths, flies, and grasshoppers', 'Least Concern', 'Tree snakes, bats, and owls', 'Has a clear third eyelid called a nictitating membrane that acts like goggles!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🐸'],
  ['Golden Poison Dart Frog', 'Phyllobates terribilis', 'The most toxic creature on planet Earth', 'Carries enough potent skin toxin to defend against any jungle predator. Its vibrant golden hue warns hungry animals to stay far away.', 'Rainforest floor of the Pacific coast of Colombia', 'Rainforest ants, termites, and small beetles', 'Endangered', 'Only the immune fire-bellied snake', 'Indigenous hunters used its secretions to coat blowgun darts!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🟡'],
  ['Axolotl', 'Ambystoma mexicanum', 'The smiling water dragon that never grows up', 'A super-cute salamander with feathery pink external gills that spends its entire life swimming in freshwater canals without morphing into a land creature.', 'Lake Xochimilco canal waterways, Mexico City', 'Worms, minnows, and freshwater insect larvae', 'Critically Endangered', 'Herons, egrets, and invasive carp', 'Can regrow lost legs, gills, and even sections of its heart and brain!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🦎'],
  ['Goliath Frog', 'Conraua goliath', 'The heavyweight king of frogs - as big as a house cat!', 'Weighing up to 7 pounds, it is the largest frog on Earth. It can jump more than 10 feet across rushing river boulders in a single bound.', 'Rushing rivers and rainforests of Cameroon and Equatorial Guinea', 'Crabs, river fish, spiders, scorpions, and small frogs', 'Endangered', 'Crocodiles, pythons, and giant water monitor lizards', 'Unlike most frogs, Goliath frogs do not have a vocal sac, so they whistle instead of croaking!', 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80', '🐸'],
  ['Blue Poison Dart Frog', 'Dendrobates tinctorius azureus', 'An electric sapphire gem of the jungle floor', 'Covered in a stunning bright sky-blue coat with ink-black freckles, this bold little frog warns every hungry bird in the jungle to stay away.', 'Isolated forest islands in southern Suriname', 'Jungle ants, mites, springtails, and caterpillars', 'Vulnerable', 'Virtually none due to bright warning toxicity', 'Each individual frog has a completely unique pattern of black spots like a fingerprint!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🔹'],
  ['Strawberry Poison Dart Frog', 'Oophaga pumilio', 'Famous for its bright red body and blue jeans legs', 'A tiny rainforest jewel that hops across the forest floor. Mother frogs carry each tadpole piggyback up into high canopy bromeliad flower pools.', 'Lowland rainforests of Costa Rica and Panama', 'Ants and mites rich in alkaloid chemistry', 'Least Concern', 'Ground snakes and large jumping spiders', 'Mothers feed their tadpoles unfertilized eggs until they grow into full froglets!', 'https://images.unsplash.com/photo-1533230678098-904c6ca9b788?auto=format&fit=crop&w=800&q=80', '🍓'],
  ['Japanese Giant Salamander', 'Andrias japonicus', 'A living river fossil dating back millions of years', 'Can grow nearly 5 feet long and spend decades crawling along cold rocky riverbeds in Japan. It breathes directly through folds in its skin.', 'Cold mountain streams in western Japan', 'River fish, crabs, worms, and stream frogs', 'Vulnerable', 'Larger giant salamanders and river otters', 'Can live for more than 70 years in pristine river waters!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🐲'],
  ['Chinese Giant Salamander', 'Andrias davidianus', 'The largest amphibian in the world', 'Reaching up to 6 feet in length, this prehistoric giant sits camouflaged among river rocks waiting to gulp down fish and river crabs.', 'Fast mountain streams of central China', 'Freshwater crabs, fish, and worms', 'Critically Endangered', 'River otters and historically humans', 'Makes vocal sounds that sound like a crying baby or barking dog!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🐉'],
  ['Hellbender', 'Cryptobranchus alleganiensis', 'The giant wrinkly snot otter of rocky rivers', 'A massive salamander with loose ruffled skin flaps that help it absorb oxygen from fast-flowing mountain streams.', 'Clear rocky mountain streams of eastern USA', 'Crayfish, minnows, and aquatic worms', 'Vulnerable', 'River otters, large trout, and northern watersnakes', 'Breathes by absorbing dissolved oxygen directly through ruffled skin folds!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🦎'],
  ['Wood Frog', 'Lithobates sylvaticus', 'The ice frog that freezes solid all winter long', 'Can survive Arctic winters by turning up to 60% of its body water into solid ice. Its heart completely stops, and it re-awakens in spring!', 'Boreal forests and tundra across North America and Alaska', 'Spiders, beetles, caterpillars, and worms', 'Least Concern', 'Garter snakes, raccoons, and red foxes', 'Produces special glucose antifreeze inside its cells to prevent ice damage!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '❄️'],
  ['Reticulated Glass Frog', 'Hyalinobatrachium valerioi', 'A transparent frog whose beating heart you can see', 'Its translucent belly skin allows you to see its internal organs, including its heart, liver, and digestive tract, beating like glass!', 'Central American rainforest stream canopies', 'Tiny river flies, moths, and aphids', 'Least Concern', 'Tree snakes, wasps, and katydids', 'Father frogs bravely guard their eggs on the undersides of leaves against predatory wasps!', 'https://images.unsplash.com/photo-1584447141399-be646c33b7d1?auto=format&fit=crop&w=800&q=80', '🔍'],
  ['Amazon Milk Frog', 'Trachycephalus resinifictrix', 'Tree frog with blue toes and sweet milk-colored skin', 'A large canopy frog with blue-gray markings and lovely golden eyes crossed by a black cross. When frightened, it secretes a milky white substance.', 'Canopy trees of the Amazon River basin', 'Crickets, moths, and tree-dwelling bugs', 'Least Concern', 'Canopy tree snakes, monkeys, and owls', 'Lays its eggs in water-filled tree hollows high above the forest floor!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🥛'],
  ['White\'s Tree Frog', 'Ranoidea caerulea', 'The cheerful chubby green tree frog', 'A calm and friendly frog with a plump body and curious gaze. It has a special waxy coating that prevents dehydration in Australian heat.', 'Forests and backyards across Australia', 'Moths, crickets, roaches, and spiders', 'Least Concern', 'Kookaburras, snakes, and feral cats', 'Can change its color from light green to dark brown to blend in with its surroundings!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🐸'],
  ['Tomato Frog', 'Dyscophus antongilii', 'A bright plump frog shaped like a ripe red tomato', 'When startled, this round Madagascar frog puffs itself up like a little ball and secretes sticky white fluid that glues predator jaws together!', 'Rainforests and marshes of eastern Madagascar', 'Insects, worms, beetles, and fly larvae', 'Least Concern', 'Colubrid snakes and wading marsh birds', 'Only females have the bright crimson red tomato color; males are yellowish-orange!', 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80', '🍅'],
  ['American Bullfrog', 'Lithobates catesbeianus', 'The booming bass croaker of freshwater lakes', 'The largest true frog in North America. Its deep, resonant jug-o-rum croak can be heard vibrating across lakes for more than half a mile.', 'Lakes, ponds, and swamps across North America', 'Insects, fish, turtles, and even small birds', 'Least Concern', 'Herons, alligators, otters, and snapping turtles', 'Can swallow whole ducklings, mice, and other frogs with its huge gaping mouth!', 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80', '🔊'],
  ['European Fire Salamander', 'Salamandra salamandra', 'Jet-black salamander with fiery yellow lightning stripes', 'Walks through damp mossy European forests after dark. Ancient folklore claimed it was born out of fires because it crawled out of logs placed on hearths.', 'Deciduous mountain forests of Central and Southern Europe', 'Earthworms, slugs, beetles, and woodlice', 'Least Concern', 'Owls, wild boars, and hedgehogs', 'Gives birth to live swimming larvae rather than laying eggs in water!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🔥'],
  ['Cane Toad', 'Rhinella marina', 'Giant rugged toad with powerful shoulder shields', 'A tough survivor that can adapt to almost any environment. It possesses large glands behind its eyes that ooze a poisonous milky fluid if bitten.', 'Forests and grasslands across Central & South America', 'Insects, small mammals, pet food, and lizards', 'Least Concern', 'Few predators; immune Keelback snakes in Australia', 'A female cane toad can lay over 30,000 eggs at a single time in water!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🟤'],
  ['African Clawed Frog', 'Xenopus laevis', 'Pancake-flat aquatic frog with sharp black claws', 'Spends its entire life swimming in muddy ponds. Lacking a tongue or teeth, it shoves food into its mouth using its fast webbed front feet.', 'Sub-Saharan African wetlands and muddy pools', 'Fish, insect larvae, worms, and tadpoles', 'Least Concern', 'Herons, kingfishers, and water snakes', 'Has three sharp black claws on each hind foot used to dig and tear food!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🐾'],
  ['Olm (Cave Salamander)', 'Proteus anguinus', 'Blind pale baby dragon of dark underground caves', 'An eel-like salamander that lives in pitch-black European cave rivers. It has no eyes, pale pink skin, and bushy bright red external gills.', 'Underground karst cave rivers of southeastern Europe', 'Cave shrimps, snails, and tiny water insects', 'Vulnerable', 'Cave-dwelling fish and larger olms', 'Can survive without eating a single bite of food for up to 10 years!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🐉'],
  ['Desert Rain Frog', 'Breviceps macrops', 'Tiny squeaking marshmallow frog of coastal dunes', 'A round, chubby frog that lives in sand dunes along the southwestern coast of Africa. When upset, it puffs up like a balloon and lets out a high-pitched squeak!', 'Sand dunes of South Africa and Namibia', 'Sand beetles, termites, and moth grubs', 'Near Threatened', 'Jackals, owls, and desert snakes', 'Does not swim or leap; it waddles across sand on short stubby feet!', 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80', '🎈']
);
list.push(
  ['Ornate Horned Frog', 'Ceratophrys ornata', 'Hungry round mouth with legs that eats anything', 'Nicknamed the Pacman frog due to its enormous round mouth and voracious appetite. It burrows in soil, waiting to ambush any prey that walks past.', 'Pampas grasslands of Argentina and Brazil', 'Mice, smaller frogs, lizards, and crickets', 'Near Threatened', 'Birds of prey and large rattlesnakes', 'Can swallow prey that is almost the exact same size as its entire body!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🟡'],
  ['Black Rain Frog', 'Breviceps fuscus', 'The grumpy-looking avocado frog of mountain slopes', 'Resembles a dark bumpy avocado with sad eyes. When agitated, it inflates its body with air like a rubber ball to wedge itself into burrows.', 'Fynbos and mist forests of southern South Africa', 'Earthworms, termites, and crawling grubs', 'Least Concern', 'Bush pigs, birds of prey, and night snakes', 'Digs backwards into the sand creating deep underground sleeping tunnels!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🥑'],
  ['Corroboree Frog', 'Pseudophryne corroboree', 'Australia\'s neon yellow and jet black stripped marvel', 'A small striking frog covered in high-visibility warning stripes. It walks slowly through high alpine snowfields and sphagnum moss bogs.', 'Alpine bogs of Mount Kosciuszko, Australia', 'Small black ants, mites, and alpine beetles', 'Critically Endangered', 'Alpine birds and introduced predatory trout', 'Synthesizes its own natural skin toxins rather than getting them from diet!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '⚡'],
  ['Golden Mantella', 'Mantella aurantiaca', 'Brilliant bright orange jewel of Madagascar', 'A dazzling little frog that looks like a fiery glowing ember on the rainforest floor. It is fully diurnal, hopping around in broad daylight.', 'Swamp forests of east-central Madagascar', 'Fruit flies, ants, termites, and springtails', 'Critically Endangered', 'Forest birds and colubrid snakes', 'Despite looking identical to South American dart frogs, it evolved independently in Madagascar!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '✨'],
  ['Wallace\'s Flying Frog', 'Rhacophorus nigropalmatus', 'Canopy frog that glides like a flying parachute', 'Possesses huge oversized webbed feet with black skin flaps that act as parachutes, allowing it to glide over 50 feet between jungle trees.', 'Canopy trees of Borneo and Malaysia', 'Flying beetles, moths, and tree crickets', 'Least Concern', 'Tree vipers, raptors, and flying lizards', 'Has suction-cup pads on its toes that stick firmly to wet, slippery jungle leaves!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🪂'],
  ['Surinam Toad', 'Pipa pipa', 'Flat leaf toad that hatches babies out of its back', 'A bizarre leaf-like toad with tiny bead eyes and sensitive star-tipped fingers. Its eggs sink into the mother\'s back, where baby toadlets develop and pop out.', 'Murky river bottoms of northern South America', 'Worms, small river fish, and crustaceans', 'Least Concern', 'Electric eels, river stingrays, and otters', 'Baby froglets sprout and swim directly out of tiny pockets on mother\'s back!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🍂'],
  ['Common Mudpuppy', 'Necturus maculosus', 'Water-puppy salamander that barks underwater', 'A completely aquatic salamander that roams lakes and rivers. It earns its puppy nickname from its vocal barking sounds and bushy red ear-gills.', 'Lakes and rivers of central North America', 'Crayfish, snails, insect nymphs, and minnows', 'Least Concern', 'Pike, bass, herons, and water snakes', 'Retains maroon bushy feather-gills throughout its entire adult life!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🐶'],
  ['Eastern Newt (Red Eft)', 'Notophthalmus viridescens', 'Bright orange wanderer of autumn woodland paths', 'Born in ponds as a swimmer, it transforms into a fiery orange land explorer called a Red Eft for years before returning to water as an olive adult.', 'Moist deciduous woodlands of eastern North America', 'Springtails, tiny snails, and insect larvae', 'Least Concern', 'Garter snakes, raccoons, and woodland crows', 'Spends up to 7 years on land as a bright orange Red Eft before becoming aquatic forever!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🍁'],
  ['California Newt', 'Taricha torosa', 'Rust-colored newt with super potent defensive toxins', 'A hardy newt that wanders redwoods and streams. When threatened, it arches its back and neck into a horseshoe shape to show its warning orange tummy.', 'Coastal redwoods and oak forests of California', 'Slugs, worms, sowbugs, and mosquito larvae', 'Least Concern', 'Garter snakes (some are resistant) and raccoons', 'Produces enough tetrodotoxin in its skin to deter coyotes, foxes, and birds!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🦎'],
  ['Rough-Skinned Newt', 'Taricha granulosa', 'In an evolutionary arms race with toxic garter snakes', 'Has bumpy grainy skin packed with potent neurotoxin. The only animal capable of eating it is the common garter snake, which has evolved resistance.', 'Pacific Northwest coastal forests from Alaska to California', 'Insects, earthworms, slugs, and amphibian eggs', 'Least Concern', 'Common garter snake with genetic toxin resistance', 'One single rough-skinned newt contains enough poison to deter multiple large predators!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🌲'],
  ['Spotted Salamander', 'Ambystoma maculatum', 'Solar-powered amphibian with bright yellow polka dots', 'A burrowing mole salamander that has bright yellow spots running down its slate-black back. It spends most of the year hidden underground.', 'Hardwood forests of eastern North America', 'Earthworms, slugs, spiders, and millipedes', 'Least Concern', 'Skunks, raccoons, and ribbon snakes', 'Algae live inside its eggs and give oxygen to the embryo in a rare solar symbiosis!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '✨'],
  ['Marbled Salamander', 'Ambystoma opacum', 'The zebra-striped woodland builder of fall nests', 'Unlike most salamanders that lay eggs in spring ponds, the marbled salamander lays eggs on dry autumn forest floors waiting for winter rain!', 'Deciduous and mixed forests of eastern USA', 'Earthworms, slugs, snails, and beetle grubs', 'Least Concern', 'Owls, foxes, and shrews', 'Female stays curled around her eggs to keep them moist until rains flood the nest!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🦓'],
  ['Eastern Tiger Salamander', 'Ambystoma tigrinum', 'The biggest land-dwelling salamander in North America', 'Covered in yellowish tiger stripes or blotches on a dark brown body. It has big friendly eyes and digs deep burrows to escape heat and cold.', 'Woodlands, grasslands, and marshes across North America', 'Worms, crickets, mice, and baby frogs', 'Least Concern', 'Badgers, snakes, and coyotes', 'Can grow over 13 inches long and live for over 25 years!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🐯'],
  ['Blue-Spotted Salamander', 'Ambystoma laterale', 'The woodland salamander flecked with sky-blue glitter', 'A sleek dark salamander dotted with sky-blue specks along its sides and tail. It produces a milky noxious defense fluid from glands on its tail.', 'Moist deciduous forests of Great Lakes and northeastern North America', 'Centipedes, earthworms, slugs, and spiders', 'Least Concern', 'Crows, raccoons, and garter snakes', 'Lashes its tail back and forth like a scorpion to show off its warning poison glands!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '💙'],
  ['Red Salamander', 'Pseudotriton ruber', 'Ruby-red mountain wanderer with golden eyes', 'A stout, gorgeous ruby salamander sprinkled with black pepper freckles. It lives near crystal-clear cold mountain springs.', 'Springs and cold creeks of eastern United States', 'Insects, earthworms, and smaller salamanders', 'Least Concern', 'Water snakes, raccoons, and woodland birds', 'Takes up to 5 whole years to transform from a water larva into an adult!', 'https://images.unsplash.com/photo-1533230678098-904c6ca9b788?auto=format&fit=crop&w=800&q=80', '❤️'],
  ['Cave Salamander', 'Eurycea lucifuga', 'The long-tailed orange acrobat of twilight cave zones', 'A bright orange salamander with irregular black spots and an extra-long prehensile tail used like a fifth leg to climb vertical cave walls.', 'Limestone caves and twilight sinkholes of southeastern USA', 'Flies, crickets, cave beetles, and spiders', 'Least Concern', 'Cave-dwelling bats and larger predatory salamanders', 'Can hang from cave ceilings using only its strong curled tail tip!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🧗'],
  ['Greater Siren', 'Siren lacertina', 'Eel-like swamp salamander that can grow 3 feet long', 'Has an eel-shaped body, bushy crimson external gills, and two tiny front legs—with no back legs at all! It thrives in murky southern swamps.', 'Cypress swamps and ditches of southeastern USA', 'Crayfish, snails, aquatic insects, and water plants', 'Least Concern', 'Alligators, mud snakes, and water birds', 'If its swamp dries up, it burrows in mud and wraps itself in a cocoon of mucus for years!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🌿'],
  ['Lesser Siren', 'Siren intermedia', 'The whispering swamp eel of southern bayous', 'A slender aquatic salamander with bushy red gills and tiny three-toed arms. It makes clicking and yelping sounds when caught or frightened.', 'Ponds, ditches, and bayous of southern and central USA', 'Snails, small clams, crustaceans, and insect larvae', 'Least Concern', 'Cottonmouth snakes, herons, and bowfin fish', 'Communicates with other sirens through series of underwater clicks and body rubs!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🐟'],
  ['Two-Toed Amphiuma', 'Amphiuma means', 'The three-foot congo snake with microscopic legs', 'Looks just like an enormous dark eel, but it is actually a salamander with four tiny legs that are barely 1/4 inch long! It possesses a very strong bite.', 'Slow-moving canals, swamps, and bayous of southeastern USA', 'Crayfish, frogs, water snakes, and small fish', 'Least Concern', 'Alligators and mud snakes', 'Has one of the largest DNA genomes of any living animal on Earth!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🐍'],
  ['Three-Toed Amphiuma', 'Amphiuma tridactylum', 'The secretive giant mud-burrower of the Mississippi', 'Similar to its two-toed cousin but sporting three tiny toes on each leg. It can grow up to 40 inches and burrows into deep river mud.', 'Floodplains and bayous of the Mississippi River basin', 'Crawfish, minnows, earthworms, and aquatic insects', 'Least Concern', 'Alligators, egrets, and cottonmouths', 'Female coils her body tightly around her egg clutch for 5 months until they hatch!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '💧']
);
list.push(
  ['Panamanian Golden Frog', 'Atelopus zeteki', 'The national treasure of Panama that signals with hand waves', 'A breathtaking bright yellow toad-like frog that lives near noisy roaring waterfalls. Because water noise drowns out croaks, it communicates by waving its hands!', 'Cloud forest stream valleys of central Panama', 'Ants, beetles, and small flies', 'Critically Endangered', 'Snakes and predatory flies', 'Practices semaphoring—waving its front limbs like flags to signal friends and rivals!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '👋'],
  ['Darwin\'s Frog', 'Rhinoderma darwinii', 'The leaf-shaped frog whose father broods babies in his throat', 'Shaped like a crunchy dry beech leaf with a pointy nose. When eggs hatch into tadpoles, the father frog gulps them into his vocal sac until they become full froglets!', 'Beech forests and cool streams of Chile and Argentina', 'Beetles, spiders, mites, and flies', 'Endangered', 'Introduced salmon, snakes, and birds', 'The dad coughs up fully formed tiny baby frogs right out of his mouth!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🍂'],
  ['Northern Leopard Frog', 'Lithobates pipiens', 'The spotted grassland athlete with Olympic leaping power', 'Covered in dark round spots surrounded by light halo borders. It can leap up to 8 feet in one bound to escape hungry meadow birds.', 'Marshes, grasslands, and ponds across northern North America', 'Beetles, flies, crickets, and spiders', 'Least Concern', 'Herons, hawks, garter snakes, and bass', 'In winter, it hibernates on the mud bottom of lakes without freezing!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🐆'],
  ['Southern Leopard Frog', 'Lithobates sphenocephalus', 'The laughing frog of southern swamps and meadows', 'Recognized by a white spot right in the center of its tympanum (ear drum). Its mating call sounds like a funny chuckling laugh.', 'Freshwater habitats across southeastern USA', 'Insects, earthworms, crayfish, and spiders', 'Least Concern', 'Alligators, snakes, and wading birds', 'Can breed during warm rains almost any month of the entire year!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '😂'],
  ['Pickerel Frog', 'Lithobates palustris', 'The rectangular-spotted frog with toxic skin secretions', 'Looks like a leopard frog, but its spots are arranged in neat rectangular rows down its back. It secretes an acidic chemical that irritates snakes.', 'Cold springs and clear streams of eastern North America', 'Spiders, ants, beetles, and sawfly larvae', 'Least Concern', 'Green herons, raccoons, and bullfrogs', 'Its skin secretion is toxic enough to kill other frogs kept in the same container!', 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80', '📐'],
  ['Spring Peeper', 'Pseudacris crucifer', 'The tiny frog with an X on its back that sings in spring', 'Barely one inch long, this tree frog produces a chorus so loud in early spring that it can be heard over a mile away. It has a distinct dark X on its back.', 'Woodland ponds and marshes of eastern North America', 'Spiders, ants, small beetles, and flies', 'Least Concern', 'Garter snakes, screech owls, and bullfrogs', 'Can withstand freezing temperatures by accumulating glucose in its blood!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🔔'],
  ['Gray Tree Frog', 'Dryophytes versicolor', 'The camouflage chameleon tree frog of North American woods', 'Can shift its skin color from lichen gray to bark brown or bright emerald green in minutes. It has bright yellow or orange patches hidden beneath its hind legs.', 'Deciduous forests across eastern North America', 'Moths, tree crickets, flies, and beetles', 'Least Concern', 'Opossums, raccoons, and tree snakes', 'Flash of bright yellow on inner thighs startles predators when it jumps!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🦎'],
  ['American Green Tree Frog', 'Dryophytes cinereus', 'The bright lime-green porch frog with a white racing stripe', 'A friendly slender green frog with a crisp white stripe along each flank. It loves sticking to house windows on warm summer nights to catch moths!', 'Wetlands, ponds, and backyard gardens of southeastern USA', 'Flies, mosquitoes, moths, and crickets', 'Least Concern', 'Rat snakes, herons, and green anoles', 'Is the official state amphibian of Georgia and Louisiana!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🌱'],
  ['Barking Tree Frog', 'Dryophytes gratiosus', 'The heaviest tree frog in the United States', 'A round, bumpy tree frog that makes a booming bark like a distant hound dog. When calling, its throat balloon inflates larger than its head!', 'Pine savannas and cypress ponds of southeastern USA', 'Arboreal crickets, beetles, and moths', 'Least Concern', 'Owls, raccoons, and coachwhip snakes', 'Spends much of the day buried deep in tree hollows or underground sand!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🐶'],
  ['Squirrel Tree Frog', 'Dryophytes squirellus', 'The little rain frog that chins down during thunderstorms', 'Earns its name from its chattering raspy call that sounds like a barking squirrel. It often calls loudly right before heavy summer rain showers.', 'Pine woods, gardens, and wetlands of southeastern USA', 'Beetles, moths, termites, and ants', 'Least Concern', 'Spiders, ribbon snakes, and small owls', 'Can completely change from yellow to emerald green to brown in 15 minutes!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🐿️'],
  ['Pacific Tree Frog', 'Pseudacris regilla', 'The famous Hollywood movie croak frog', 'Whenever movies need a background frog sound, filmmakers almost always play the ribbit of this little west-coast frog! It has a bold black eye-mask.', 'Ponds, woodlands, and urban gardens along Pacific coast of North America', 'Flies, beetles, spiders, and caterpillars', 'Least Concern', 'Garter snakes, raccoons, and blue jays', 'Its ribbit-ribbit sound is the universal standard frog noise in Hollywood cinema!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🎬'],
  ['Western Toad', 'Anaxyrus boreas', 'The mountain wanderer with a creamy white dorsal stripe', 'A large, dry-skinned toad with a creamy stripe running right down the middle of its back. It walks rather than hops, traveling miles across forests.', 'Mountain meadows, forests, and wetlands of western North America', 'Beetles, ants, sowbugs, and spiders', 'Near Threatened', 'Ravens, garter snakes, and coyotes', 'Lacks a vocal sac, so it lets out a quiet chirping sound like a baby chick!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🏔️'],
  ['Yosemite Toad', 'Anaxyrus canorus', 'The high-altitude musical toad of the Sierra Nevada', 'Living high in alpine meadows over 10,000 feet up, males serenade females with a long melodious musical trill that echoes across granite valleys.', 'High-elevation alpine meadows of Sierra Nevada, California', 'Alpine beetles, flies, and caterpillars', 'Endangered', 'Clark\'s nutcrackers, garter snakes, and trout', 'Male and female look so different in coloration that early scientists thought they were separate species!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🎶'],
  ['Fowler\'s Toad', 'Anaxyrus fowleri', 'The beach and forest toad with a wailing baby cry', 'A common North American toad recognized by having three or more bumps inside each large dark spot. Its call sounds like a crying sheep or baby!', 'Sandy woodlands, river valleys, and beaches of eastern USA', 'Earthworms, beetles, ants, and sowbugs', 'Least Concern', 'Hognose snakes, skunks, and raccoons', 'Eastern hognose snakes are specially adapted to eat them, being immune to their toad poisons!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🐑'],
  ['Oak Toad', 'Anaxyrus quercicus', 'The smallest toad in North America with a fiery back stripe', 'Barely the size of a quarter (less than an inch long), this tiny toad has a bright orange or yellow line down its back and chirps like a baby chick.', 'Longleaf pine flatwoods and oak scrub of southeastern USA', 'Ants, tiny beetles, and springtails', 'Least Concern', 'Garter snakes, hognose snakes, and spiders', 'Its vocal sac inflates into a huge white balloon that is bigger than its entire body!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🪙'],
  ['Midwife Toad', 'Alytes obstetricans', 'The caring father toad that carries eggs on his legs', 'A small European toad famous for fatherly devotion: the male wraps strings of eggs around his hind legs and carries them everywhere for a month until they hatch!', 'Hillsides, old stone walls, and quarries across Western Europe', 'Beetles, crickets, slugs, and worms', 'Least Concern', 'Vipers, owls, and hedgehogs', 'The dad dips his legs into puddles at night to make sure his eggs never dry out!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🥚'],
  ['Common Spadefoot Toad', 'Pelobates fuscus', 'The nocturnal garlic-scented digging champion', 'Features sharp black spade-like keratin spurs on its hind feet that allow it to dig backwards into sand in seconds. When threatened, it smells like garlic!', 'Sandy plains, dunes, and farmland across Europe', 'Nocturnal beetles, crickets, and earthworms', 'Least Concern', 'Badgers, owls, and grass snakes', 'Can bury itself completely underground in less than 30 seconds!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🧄'],
  ['Mexican Burrowing Toad', 'Rhinophrynus dorsalis', 'The subterranean balloon toad with an anteater snout', 'A plump cone-headed toad that spends almost its entire life underground eating ants and termites with its specialized sticky cone tongue.', 'Lowland savannas and dry scrub of Mexico and Central America', 'Underground termites and ants', 'Least Concern', 'Coatis, skunks, and ground snakes', 'Has an internal shovel bone in its hind feet made specifically for digging backwards through clay!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🐜'],
  ['Indian Purple Frog', 'Nasikabatrachus sahyadrensis', 'The purple living dinosaur frog discovered in 2003', 'Looks like a bloated purple jelly doughnut with a tiny pointy snout. It spends all but two weeks of the year burrowed deep underground in India.', 'Western Ghats mountain rainforests of southern India', 'Underground termites', 'Near Threatened', 'Wild boars and civet cats', 'It remained undiscovered by modern science until 2003 because it only surfaces to mate during monsoons!', 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80', '🟣'],
  ['Vietnamese Mossy Frog', 'Theloderma corticale', 'The ultimate master of disguise disguised as moss', 'Every bump, spine, and ridge on its green and brown body perfectly mimics living tree moss. When scared, it plays dead by curling into a mossy ball!', 'Flooded caves and rocky riverbanks of northern Vietnam', 'Crickets, roaches, moths, and flies', 'Least Concern', 'Tree vipers and forest rodents', 'When touched by a predator, it curls into a stiff ball and rolls away like a lump of moss!', 'https://images.unsplash.com/photo-1584447141399-be646c33b7d1?auto=format&fit=crop&w=800&q=80', '🌿']
);
list.push(
  ['Clown Tree Frog', 'Dendropsophus leucophyllatus', 'The colorful geometric pattern painter of the Amazon', 'A dazzling small tree frog patterned in striking yellow, chocolate-brown, and pink stripes that resemble a clown costume.', 'Flooded tropical rainforests of South America', 'Moths, flies, and canopy insects', 'Least Concern', 'Tree vipers, owls, and monkeys', 'Lays its eggs on leaves right over water pools so hatching tadpoles drop directly into the pool!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🤡'],
  ['Dyeing Dart Frog', 'Dendrobates tinctorius', 'The giant dart frog named after an ancient myth', 'One of the largest poison dart frogs, featuring black skin with brilliant yellow or white stripes. Legend said native tribes used them to change parrot feather colors!', 'Rainforest floors of French Guiana, Guyana, and Suriname', 'Forest ants, termites, and tiny beetles', 'Least Concern', 'Large rainforest spider species', 'Males are devoted fathers that transport tadpoles on their backs one by one to high tree reservoirs!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🦜'],
  ['Splash-Backed Dart Frog', 'Ranitomeya variabilis', 'The jewel-like miniature tree explorer', 'A tiny frog barely half an inch long, with shimmering turquoise legs and a bright yellow-splashed back. It spends its life climbing high canopy vines.', 'Amazon rainforest of Peru, Ecuador, and Colombia', 'Ants, mites, and tiny woodlice', 'Least Concern', 'Small crab spiders and canopy lizards', 'Lays only two eggs at a time inside bromeliad leaf pools!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🎨'],
  ['Bumblebee Dart Frog', 'Dendrobates leucomelas', 'The yellow-and-black striped thunder frog', 'Sporting wide bold yellow and jet-black bands like a bumblebee, this frog starts calling loudly right as tropical rainstorms approach.', 'Moist tropical rainforests of Venezuela and Brazil', 'Ants, termites, and fruit flies', 'Least Concern', 'Few predators; toxic batrachotoxin protects it', 'Can enter a dormant state during dry seasons to protect its moist skin!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🐝'],
  ['Granular Poison Frog', 'Oophaga granulifera', 'The bumpy bright scarlet jumper of Central America', 'Features bright red or orange bumpy skin on its back with green or blue legs. Its bumpy texture and warning colors scream poison to hungry birds.', 'Lowland humid rainforests of Costa Rica and Panama', 'Ants and alkaloid-rich mites', 'Vulnerable', 'Crab spiders and snakes', 'Mothers lay unfertilized eggs to feed each of their tadpoles inside canopy plants!', 'https://images.unsplash.com/photo-1533230678098-904c6ca9b788?auto=format&fit=crop&w=800&q=80', '🔴'],
  ['Phantasmal Poison Frog', 'Epipedobates anthonyi', 'The tiny crimson singer that produces medicinal compound', 'A diminutive frog with brilliant ruby-red skin adorned with creamy white stripes. Scientists discovered a painkiller 200 times stronger than morphine in its skin!', 'Tropical highland rainforest streams of Ecuador and Peru', 'Ants, flies, and fruit flies', 'Near Threatened', 'Water snakes and birds', 'Its skin compound epibatidine has been studied by scientists to create revolutionary pain medicines!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '💊'],
  ['Harlequin Toad', 'Atelopus varius', 'The living rainbow jewel of mountain streams', 'Decorated in dazzling mosaics of neon green, hot pink, orange, and pitch black. It walks slowly along rushing mountain streams.', 'Fast-flowing streams in Costa Rica and western Panama', 'Small flies, beetles, and river nymphs', 'Critically Endangered', 'Parasitic flesh-eating flies', 'Has undergone successful conservation captive breeding after being saved from fungal threats!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🎭'],
  ['Titicaca Water Frog', 'Telmatobius culeus', 'The wrinkly scrotum frog of high mountain lakes', 'Lives entirely underwater at 12,500 feet elevation in Lake Titicaca. Its body is covered in huge folds of loose wrinkly skin used to breathe underwater without lungs!', 'Lake Titicaca in Bolivia and Peru', 'Amphipods, snails, water bugs, and fish', 'Critically Endangered', 'Gulls, grebes, and large trout', 'Does underwater push-ups to keep fresh water flowing over its wrinkly skin folds!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🌊'],
  ['Lake Junin Giant Frog', 'Telmatobius macrostomus', 'The prehistoric giant of the Peruvian Andes', 'One of the largest fully aquatic frogs in the world, growing over a foot long. It lives in cold Andean lake waters where oxygen is scarce.', 'Lake Junin and connecting rivers in Peru', 'Small fish, snails, and aquatic bugs', 'Endangered', 'Andean gulls, grebes, and introduced trout', 'Has such reduced lungs that it breathes almost 100% through its skin!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🏔️'],
  ['Helmeted Water Toad', 'Calyptocephalella gayi', 'The giant prehistoric armored water beast of Chile', 'Can grow up to 12 inches long and weigh over 6 pounds! It has an armored bony skull and sits on river beds like a living aquatic boulder.', 'Deep rivers and lakes of central Chile', 'Fish, frogs, waterbirds, and crayfish', 'Vulnerable', 'Introduced trout, birds of prey, and otters', 'Is a living dinosaur-age fossil that has survived practically unchanged for 40 million years!', 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80', '🛡️'],
  ['Spanish Ribbed Newt', 'Pleurodeles waltl', 'The real-life Wolverine newt with piercing rib spikes', 'When attacked, this amazing newt rotates its sharp ribs so they punch through its own skin to poke predators with toxic bone spears!', 'Ponds and slow streams of Spain, Portugal, and Morocco', 'Aquatic insects, worms, and tadpoles', 'Near Threatened', 'Storks, herons, and predatory fish', 'Its skin heals completely in days after its ribs pierce through to defend itself!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '⚔️'],
  ['Alpine Newt', 'Ichthyosaura alpestris', 'The vibrant blue dragon of European mountain tarns', 'During spring breeding, males turn iridescent royal blue with black-and-white spotted racing stripes and a fiery pumpkin-orange belly.', 'Forest pools and alpine lakes across Central Europe', 'Water fleas, mosquito larvae, and worms', 'Least Concern', 'Trout, dragonflies, and grass snakes', 'Can live in icy glacial lakes up to 8,000 feet above sea level!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '💙'],
  ['Great Crested Newt', 'Triturus cristatus', 'The mini freshwater sea dragon with jagged dorsal crest', 'During spring, male newts grow a magnificent jagged dragon-crest running along their back and tail, which they fan to woo females.', 'Deep, weed-rich ponds across Britain and Europe', 'Water beetles, snails, and tadpoles', 'Least Concern', 'Herons, pike, and grass snakes', 'Can live for over 15 years in clean protected wetland ponds!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🐉'],
  ['Smooth Newt', 'Lissotriton vulgaris', 'The gentle garden pond explorer of Britain', 'The most common newt across northern Europe. It spends spring in ponds dancing with wavy tail crests and moves into damp garden rocks in summer.', 'Garden ponds, wetlands, and woodland ditches across Europe', 'Midges, water fleas, slugs, and worms', 'Least Concern', 'Kingfishers, grass snakes, and hedgehogs', 'Courtship involves the male curling his tail into a whip to waft pheromones to the female!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🌿'],
  ['Palmate Newt', 'Lissotriton helveticus', 'The moorland swimmer with webbed black paddle toes', 'A delicate newt that thrives in acidic moorland and heathland ponds where other amphibians cannot survive. Males have black webbed hind feet.', 'Heaths, bogs, and moorland pools of Western Europe', 'Water boatmen, mosquito larvae, and tiny worms', 'Least Concern', 'Mallards, moorhens, and dragonfly larvae', 'Can tolerate acidic peat bog waters with a pH as low as 4.0!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🦆'],
  ['Banded Newt', 'Ommatotriton vittatus', 'The high-crested knight newt of the Middle East', 'Male grows an impossibly tall, serrated silver-and-black crest like a knight\'s armor during breeding season, flashing brilliant silvery flanks.', 'Spring-fed ponds and marshy woodlands of Turkey and Levant', 'Aquatic insects, worms, and water fleas', 'Least Concern', 'Water snakes, egrets, and river crabs', 'Its breeding crest is so tall it accounts for nearly half its body height!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🛡️'],
  ['Corsican Fire Salamander', 'Salamandra corsica', 'The golden-blotched island jewel of Corsica', 'An ancient salamander found only on the Mediterranean island of Corsica. It has bright circular golden coins splashed across velvet black skin.', 'Beech and chestnut forests of Corsica', 'Spiders, slugs, earthworms, and beetles', 'Least Concern', 'Owls and wild boar', 'Found strictly on Corsica and nowhere else on the entire planet!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🏝️'],
  ['Lusitanian Salamander', 'Chioglossa lusitanica', 'The lightning-fast lizard-like salamander of Iberia', 'Unlike most slow salamanders, this species runs with the agility of a lizard and can shoot its tongue out like a chameleon to snatch flies!', 'Mossy granite streams of Portugal and northwestern Spain', 'Flies, gnats, spiders, and tiny beetles', 'Vulnerable', 'Trout and northern viper snakes', 'Can shed and regrow its entire tail just like a lizard when grabbed by a bird!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '⚡'],
  ['Ensatina Salamander', 'Ensatina eschscholtzii', 'The famous ring species explorer of Pacific coast forests', 'A woodland salamander that formed a famous unbroken evolutionary ring around California\'s Central Valley. It carries poison glands in its fat tail.', 'Redwood and coastal oak forests of western North America', 'Spiders, sowbugs, springtails, and termites', 'Least Concern', 'Garter snakes, scrub jays, and raccoons', 'When attacked, it drops its tail, which continues twitching wildly to distract the predator!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🦎'],
  ['Arboreal Salamander', 'Aneides lugubris', 'The tree-climbing salamander with razor-sharp teeth', 'Possesses prehensile toes and sharp teeth capable of giving a surprisingly painful defensive nip. It climbs oak trees up to 60 feet high!', 'Oak woodlands and coastal forests of California', 'Wood-boring beetles, termites, and spiders', 'Least Concern', 'Owls, scrub jays, and kingsnakes', 'Can squeak or bark audibly when disturbed in tree hollows!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🌳'],
  ['Red-Backed Salamander', 'Plethodon cinereus', 'The lungless forest dweller that breathes through its skin', 'Has no lungs whatsoever; it absorbs 100% of its oxygen directly through damp skin. It is one of the most abundant vertebrates in eastern North America!', 'Deciduous forest leaf litter across eastern North America', 'Springtails, mites, earthworms, and spiders', 'Least Concern', 'Shrews, woodland thrushes, and garter snakes', 'In many eastern forests, the total weight of red-backed salamanders exceeds that of all birds combined!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🍂'],
  ['Slimy Salamander', 'Plethodon glutinosus', 'The super-glue defender of woodland logs', 'When handled, it coats itself in an impossibly sticky glue-like secretion that is harder to wash off than rubber cement, fouling predator jaws!', 'Moist forested ravines across eastern USA', 'Ants, beetles, sowbugs, and earthworms', 'Least Concern', 'Woodland mice, shrews, and raccoons', 'Its defensive glue takes hours to scrub off hands and can stick predator jaws shut!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🪵'],
  ['Ringed Caecilian', 'Siphonops annulatus', 'The underground baby feeder that sheds its own skin for food', 'A legless, shiny black amphibian ringed with bright white stripes. Mother caecilians grow a specialized outer layer of fatty skin that baby pups eat with special teeth!', 'Tropical rainforest soil of South America', 'Earthworms, termites, and subterranean insect grubs', 'Least Concern', 'Coral snakes and burrowing monitor lizards', 'Babies feed by gently stripping nutritious skin off mother\'s body without harming her!', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80', '🪱'],
  ['Aquatic Caecilian', 'Typhlonectes natans', 'The completely aquatic legless swimmer of riverbeds', 'A freshwater aquatic caecilian with smooth rubbery skin that undulates through tropical rivers like a friendly underwater eel.', 'Rivers, lakes, and marshes of Colombia and Venezuela', 'Aquatic worms, small minnows, and insect larvae', 'Least Concern', 'Caiman, giant river otters, and large catfish', 'Gives birth to live swimming pups with giant fan-like external gills!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🌊'],
  ['Boettger\'s Caecilian', 'Gymnopis multiplicata', 'The armored skull burrower of Central America', 'Possesses an extremely solid bone skull designed like a mini bulldozer to tunnel through packed jungle soil in search of prey.', 'Humid lowland forests of Central America', 'Earthworms, beetle larvae, and termites', 'Least Concern', 'Burrowing snakes and armadillos', 'Has tiny sensory tentacles near its eyes that smell and feel underground!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '⛏️'],
  ['Mountain Chicken Frog', 'Leptodactylus fallax', 'The giant Caribbean ditch frog named after roast chicken', 'One of the largest frogs in the world, growing up to 8 inches. Locals historically said it tasted just like chicken, giving it its funny name!', 'Rainforest valleys of Dominica and Montserrat', 'Crickets, millipedes, tarantulas, and small bats', 'Critically Endangered', 'Feral cats, rats, and mongooses', 'Mother frogs lay a foam nest in burrows and feed up to 50 tadpoles with infertile eggs!', 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80', '🍗'],
  ['Budgett\'s Frog', 'Lepidobatrachus laevis', 'The screaming funny-faced frog of South American swamps', 'A flat round frog with eyes perched right on top of its head. When cornered, it inflates with air, opens a huge toothy mouth, and emits a loud screech!', 'Chaco seasonal floodplains of Paraguay and Argentina', 'Fish, frogs, water bugs, and crabs', 'Least Concern', 'Herons and water snakes', 'Has two sharp fang-like bony projections in its lower jaw to grip slippery fish!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '😱'],
  ['Common European Frog', 'Rana temporaria', 'The familiar green-brown jumper of European ponds', 'Found across gardens, meadows, and lakes from Britain to Russia. In spring, males produce sweet croaking choruses and lay giant jelly egg masses.', 'Ponds, wet woodlands, and gardens across Europe', 'Insects, earthworms, snails, and slugs', 'Least Concern', 'Herons, grass snakes, hedgehogs, and pike', 'Can survive winters in northern Scandinavia by hibernating under ice!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🐸'],
  ['Green and Golden Bell Frog', 'Ranoidea aurea', 'The sunbathing metallic wonder of Australia', 'Unlike most frogs that stay hidden, this Australian species loves basking in direct hot sunshine. It has shimmering gold and pea-green patches.', 'Wetlands, reed beds, and coastal quarries of eastern Australia', 'Insects, worms, crayfish, and smaller frogs', 'Vulnerable', 'Kookaburras, red-bellied black snakes, and foxes', 'Its mating call sounds like a little motor engine starting up and grunting!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🔔'],
  ['Striped Marsh Frog', 'Limnodynastes peronii', 'The tennis-ball popping frog of Australian marshes', 'A handsome frog with rich dark chocolate stripes down its back. Its rapid calling sounds exactly like a tennis ball being struck with a racket: tok-tok!', 'Swamps, dams, and creek beds of eastern Australia', 'Beetles, bugs, spiders, and water boatmen', 'Least Concern', 'Water monitors, wading birds, and snakes', 'Lays its eggs inside a whipped floating foam raft that looks like whipped cream!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🎾'],
  ['European Green Toad', 'Bufotes viridis', 'The emerald-marbled desert survivor with ruby eye specks', 'Decorated in beautiful emerald-green camouflage patches over a light cream body. It can thrive in arid urban gardens and coastal sand dunes.', 'Grasslands, steppes, and urban areas across Southern Europe', 'Beetles, ants, moths, and caterpillars', 'Least Concern', 'Barn owls, hedgehogs, and grass snakes', 'Has one of the highest salt and drought tolerances of any European amphibian!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '💚'],
  ['Natterjack Toad', 'Epidalea calamita', 'The running toad with a yellow racing stripe down its spine', 'Instead of hopping, this unique European toad sprints across sand dunes on fast little legs. It has a bright lemon-yellow racing stripe running down its back.', 'Coastal sand dunes and sandy heaths of Western Europe', 'Beetles, sand ants, and spiders', 'Least Concern', 'Gulls, crows, foxes, and hedgehogs', 'Its loud raspy call can be heard from several miles away on quiet spring nights!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🏃'],
  ['Waxy Monkey Leaf Frog', 'Phyllomedusa sauvagei', 'The calm tree climber that bathes in protective sun wax', 'A remarkable frog that walks slowly like a monkey rather than hopping. It produces a natural wax from glands on its neck and rubs it all over its body to avoid drying out.', 'Dry Gran Chaco woodlands of Argentina and Paraguay', 'Moths, crickets, roaches, and flies', 'Least Concern', 'Tree vipers and birds of prey', 'Rubs waterproof wax over its entire skin with its hands and feet, like applying sunscreen!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🧴'],
  ['Cascades Frog', 'Rana cascadae', 'The high mountain gold-eyed jumper of alpine ponds', 'A honey-gold frog with copper flecks that inhabits alpine tarns and glacial streams near Mount Rainier and Mount Shasta.', 'Cascade Mountains of Washington, Oregon, and northern California', 'Caddisflies, water striders, mayflies, and spiders', 'Near Threatened', 'Garter snakes, trout, and water ouzels', 'Can survive underneath meters of mountain winter snow for up to 9 months!', 'https://images.unsplash.com/photo-1579380656108-328e8042d0ae?auto=format&fit=crop&w=800&q=80', '🏔️']
);

const mapped = list.map((s, i) => ({
  id: 'amphibian-' + (i + 1),
  name: s[0],
  scientific: s[1],
  category: 'amphibians',
  tagline: s[2],
  description: s[3],
  habitat: s[4],
  diet: s[5],
  endangered: s[6],
  predators: s[7],
  funFact: s[8],
  image: s[9],
  emoji: s[10]
}));

const outPath = path.join(__dirname, '..', 'data', 'amphibians.js');
const js = '// 94 Amphibians Data File\nwindow.AMPHIBIANS_DATA = ' + JSON.stringify(mapped, null, 2) + ';\n';
fs.writeFileSync(outPath, js, 'utf8');
console.log('Successfully wrote data/amphibians.js with ' + mapped.length + ' species!');
