const fs = require('fs');
const path = require('path');

const list = [];

list.push(
  ['Monarch Butterfly', 'Danaus plexippus', 'The iconic orange migrator that flies across North America', 'Famous for their brilliant stained-glass orange and black wings. They embark on an epic 3,000-mile autumn migration to the mountaintop oyamel fir forests of central Mexico!', 'Meadows, prairies, gardens, and roadsides across North America', 'Herbivore (Nectarivore) - flower nectar; caterpillars eat only milkweed', 'Endangered', 'Orioles, grosbeaks, praying mantises, and spiders', 'Monarch caterpillars store toxic cardenolides from milkweed plants, making adult butterflies poisonous and distasteful to birds!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🦋'],
  ['Atlas Moth', 'Attacus atlas', 'The giant winged titan with snake-head wingtips', 'One of the largest insects in the world, with a wingspan stretching nearly 10 inches across. The tips of its wings look shockingly like the head of a deadly cobra poised to strike!', 'Tropical rainforests of Southeast Asia', 'Does not eat as an adult (lacks a mouth!); caterpillars eat cinnamon and citrus leaves', 'Least Concern', 'Insectivorous birds, bats, and tree lizards', 'Adults live for only one to two weeks, relying purely on fat reserves stored from their caterpillar days!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🦇'],
  ['Hercules Beetle', 'Dynastes hercules', 'The super-strong heavyweight titan with massive battle pincers', 'Males boast colossal curved pincers that make them look like robotic gladiators. They can lift objects over 100 times their own body weight in treetop battles!', 'Tropical rainforests of Central and South America', 'Herbivore - rotting fruit, plant sap, and fallen peach palms', 'Least Concern', 'Toucan birds, coatimundis, and large tree boas', 'Their hard shell changes color from khaki-green in dry air to jet black in high humidity!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🪲'],
  ['Orchid Mantis', 'Hymenopus coronatus', 'The pink flower disguise hunter that fools pollinating bees', 'A breathtaking pink and white praying mantis whose walking legs are shaped like soft flower petals. It perches silently inside orchid flowers, waiting for prey to land on it!', 'Tropical rainforests of Southeast Asia and Malaysia', 'Carnivore - bees, butterflies, hoverflies, and small crickets', 'Least Concern', 'Larger birds, geckos, and tree frogs', 'Pollinating insects are actually more attracted to the mantis than to the real orchid flower itself!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🌸'],
  ['Bullet Ant', 'Paraponera clavata', 'The jungle warrior with the most painful sting on Earth', 'A giant black ant measuring over an inch long. Its sting is rated a maximum 4.0+ on the Schmidt Pain Index, described as like walking on burning coals with a 3-inch rusty nail in your heel!', 'Lowland rainforest canopies and floors of Central and South America', 'Omnivore - tree sap, honeydew, small katydids, and caterpillars', 'Least Concern', 'Phorid parasitic flies and anteaters', 'Indigenous Sateré-Mawé people of Brazil wear gloves filled with bullet ants in a legendary rite of passage!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🐜'],
  ['Western Honeybee', 'Apis mellifera', 'The fuzzy pollen queen that powers life on Earth', 'Living in colonies of up to 60,000 workers, honeybees communicate the location of blooming flowers through a sophisticated 8-figure figure dance called the waggle dance!', 'Meadows, orchards, gardens, and farms worldwide', 'Herbivore - flower nectar and protein-rich pollen', 'Vulnerable', 'Hornets, bears, bee-eater birds, and skunks', 'A single honeybee worker produces only about 1/12th of a teaspoon of honey in her entire lifetime!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🐝'],
  ['Luna Moth', 'Actias luna', 'The glowing lime-green moon spirit of woodland nights', 'A magnificent pale green moth with trailing ribbon-like tails on its hindwings. The wavy tails disrupt the sonar echolocation of hunting bats, causing bats to miss their attacks!', 'Deciduous hardwood forests of North America', 'Adults do not feed; caterpillars munch on birch, hickory, and walnut leaves', 'Least Concern', 'Bats, screech owls, and whip-poor-wills', 'Spins their tails in circles during flight to confuse hunting bats using ultrasound!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🌙'],
  ['European Praying Mantis', 'Mantis religiosa', 'The stealthy kung-fu hunter with 3D stereo vision', 'Holds its spiky front raptorial legs folded in a prayer pose, then strikes at prey in less than 1/20th of a second! It can swivel its triangular head 180 degrees.', 'Meadows, gardens, and shrubby hillsides worldwide', 'Carnivore - moths, flies, crickets, and occasionally hummingbirds', 'Least Concern', 'Songbirds, bullfrogs, chameleons, and bats', 'Is the only insect capable of turning its head around to look over its shoulder!', 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80', '🦗'],
  ['Emperor Dragonfly', 'Anax imperator', 'The supersonic aerial ace with a 95% hunt success rate', 'One of the most efficient apex hunters in the animal kingdom! Its 30,000 lens facets let it calculate vector interception paths and catch flies mid-air.', 'Ponds, lakes, and slow-moving rivers across Europe and Africa', 'Carnivore - mosquitoes, midges, flies, butterflies, and smaller damselflies', 'Least Concern', 'Hobbys (falcons), kingfishers, and large frogs', 'Dragonflies have been flying through Earth\'s skies for over 300 million years, long before dinosaurs!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🚁'],
  ['Leafcutter Ant', 'Atta cephalotes', 'The miniature jungle farmers that grow their own mushroom gardens', 'Carries bright green leaf flags in long winding highways across the rainforest floor. They do not eat the leaves—they chew them into mulch to farm subterranean edible fungi!', 'Tropical rainforests of Central and South America', 'Herbivore (Fungivore) - specifically cultivated fungal colonies', 'Least Concern', 'Anteaters, armadillos, army ants, and phorid flies', 'A single leafcutter colony can contain 8 million ants and excavate over 40 tons of soil underground!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🍃'],
  ['Periodical Cicada', 'Magicicada septendecim', 'The 17-year underground slumber party that awakens in billions', 'Spends 17 whole years underground drinking sap from tree roots, then crawls out simultaneously with billions of brethren in an unforgettable deafening summer songfest.', 'Deciduous hardwood forests of eastern United States', 'Herbivore - xylem fluids from tree twigs and roots', 'Least Concern', 'Practically every woodland bird, mammal, and fish', 'Emerging in prime-numbered years (13 and 17) prevents local predators from syncing their life cycles with them!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '⏰'],
  ['Common Eastern Firefly', 'Photinus pyralis', 'The blinking lightning bug that turns summer meadows into magic', 'Lights up evening twilight with cold bioluminescent flashes produced in its abdomen. Males flash specific light patterns while flying, and females flash back from grass blades.', 'Moist fields, meadows, and forest edges of North America', 'Carnivore as larvae (slugs and snails); adults consume nectar or do not eat', 'Least Concern', 'Spiders, toads, and bats', 'Their light is 100% efficient—unlike lightbulbs, practically zero energy is wasted as heat!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '💡'],
  ['Goliath Beetle', 'Goliathus goliatus', 'The flying tank of the African rainforest canopy', 'Among the heaviest insects on Earth, weighing up to 3.5 ounces in the larval stage! When adults fly, their huge wings make a loud whirring sound like a toy helicopter.', 'Equatorial rainforests of Central and Western Africa', 'Herbivore - tree sap, fermenting fruit, and nectar', 'Least Concern', 'Birds of prey, genets, and baboons', 'Their larvae can grow as heavy as an apple before transforming into armored winged beetles!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🪲'],
  ['Blue Morpho Butterfly', 'Morpho peleides', 'The dazzling blue mirror that glints across the canopy', 'Wings are not actually blue—they are covered in microscopic pyramid scales that reflect blue light, creating an unbelievable metallic shimmer visible from a quarter-mile away!', 'Tropical rainforests of Central and South America', 'Frugivore - rotting mangoes, fermenting fruit, and tree sap', 'Least Concern', 'Jacamars, flycatchers, tree frogs, and spiders', 'When perched with closed wings, its brown undersides with owl-eye spots make it look like a dry leaf!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🦋'],
  ['Giant Walking Stick', 'Phryganistria chinensis', 'The two-foot living twig that sways in the wind', 'Can grow over 25 inches long with legs extended, holding the record as one of the longest insects on the planet. It mimics the gentle swaying of a branch in the breeze.', 'Mountain forests of southwestern China', 'Herbivore - leaves of oak, bramble, and eucalyptus trees', 'Least Concern', 'Birds, monkeys, mantises, and lizards', 'Can regenerate lost legs when molting as a young nymph!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🎋'],
  ['Buff-Tailed Bumblebee', 'Bombus terrestris', 'The fuzzy pollinator that shakes flowers with buzz pollination', 'Coated in dense velvety hairs to stay warm in freezing mountain weather. They grab flower petals and vibrate their flight muscles at high frequency to shake pollen loose!', 'Meadows, gardens, and alpine fields of Europe and Asia', 'Herbivore - nectar and pollen from lupines, clover, and borage', 'Least Concern', 'Badgers, bee-eaters, crab spiders, and skunks', 'Can fly in weather that is far too cold for regular honeybees because their thick fur insulates them!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🐝'],
  ['Asian Giant Hornet', 'Vespa mandarinia', 'The two-inch armored titan with a venomous needle', 'The world\'s largest hornet, sporting an orange head, brown thorax, and a 1/4-inch stinger. Scout hornets mark bee hives with pheromones for group raids.', 'Temperate and tropical mountain forests of East Asia', 'Carnivore - honeybees, mantises, beetles, and hornets', 'Least Concern', 'Crested honey buzzards and badgers', 'Can fly up to 25 mph and travel over 60 miles in a single day!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '⚠️'],
  ['Seven-Spotted Ladybug', 'Coccinella septempunctata', 'The gardener\'s best friend that munches 5,000 aphids', 'A round, shiny scarlet beetle marked with seven black polka dots. When touched, it reflex-bleeds noxious yellow droplets from its knee joints to deter birds.', 'Meadows, gardens, farms, and scrublands across Europe and North America', 'Carnivore - aphids, scale insects, whiteflies, and mites', 'Least Concern', 'Swifts, swallows, assassin bugs, and spiders', 'A single ladybug can consume more than 5,000 pest aphids over its lifespan!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🐞'],
  ['Rhinoceros Beetle', 'Oryctes nasicornis', 'The armored gladiator with an impressive upward horn', 'Sporting a massive recurved horn on its head like a miniature prehistoric rhino, males duel on tree trunks to push rivals off branches.', 'Oak woods, parks, and compost heaps across Europe and Mediterranean', 'Herbivore - tree sap, decaying bark, and rotten wood fiber', 'Least Concern', 'Tawny owls, magpies, and wild boars', 'Can carry loads weighing up to 850 times their own body mass!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🦏'],
  ['Eastern Carpenter Bee', 'Xylocopa virginica', 'The shiny bumblebee lookalike that drills wooden galleries', 'Resembles a bumblebee, but has a shiny black hairless abdomen. Females use their powerful jaws to drill perfectly round 1/2-inch tunnels into weathered wood.', 'Deciduous forests and residential yards across eastern North America', 'Herbivore - nectar and pollen from flowers', 'Least Concern', 'Woodpeckers (who drill into bee tunnels to eat larvae) and robber flies', 'Males hover protectively near nests like mini helicopters, but they have no stinger at all!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🪵'],
  ['Army Ant', 'Eciton burchellii', 'The nomadic million-soldier swarm of the jungle', 'Does not build permanent nests; millions of workers form temporary living bivouacs out of their own interlocking claws, marching daily in a vast predatory carpet.', 'Tropical rainforest floor of Central and South America', 'Carnivore - tarantulas, scorpions, crickets, lizards, and wasps', 'Least Concern', 'Antbirds (which follow the swarm to snatch fleeing insects) and chimango caracaras', 'Soldier ants have enormous curved hook jaws that lock shut like dental forceps!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🐜'],
  ['Ebony Jewelwing Damselfly', 'Calopteryx maculata', 'The emerald-green river dancer with velvet black wings', 'Flutters gently along clear shaded woodland brooks like a little iridescent butterfly. Males display metallic emerald bodies and jet-black wings during courtship dances.', 'Clear, slow woodland streams of eastern North America', 'Carnivore - mosquitoes, gnats, water bugs, and midges', 'Least Concern', 'Frogs, dragonflies, water striders, and trout', 'Courting males perform aerial acrobatics and hover backward in midair to impress females!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '💎'],
  ['True Katydid', 'Pterophylla camellifolia', 'The noisy green leaf caller of summer canopies', 'High in oak and maple treetops, their abrasive calling of Katy-did, Katy-didn\'t fills hot summer nights. Their broad green wings mimic ribbed tree leaves.', 'Deciduous tree canopies of eastern North America', 'Herbivore - leaves of oak, sweetgum, and maple trees', 'Least Concern', 'Owls, bats, squirrels, and arboreal snakes', 'Their ears are located not on their heads, but on their front legs just below the knee joints!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🍃'],
  ['Six-Spotted Tiger Beetle', 'Cicindela sexguttata', 'The metallic emerald cheetah of forest pathways', 'Runs so fast across sunlit forest paths (over 5 mph relative to size) that its eyes cannot process images fast enough, forcing it to stop periodically to see where it is!', 'Sunny woodland trails and forest floors of eastern North America', 'Carnivore - ants, spiders, caterpillars, and flies', 'Least Concern', 'Robber flies, dragonflies, and thrushes', 'Has sickle-shaped jaws with interlocking teeth that clamp onto prey with lightning speed!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🐅'],
  ['Stag Beetle', 'Lucanus cervus', 'The antlered monarch of European oak forests', 'The largest terrestrial insect in Britain and Central Europe. Males boast massive antler-like mandibles that they use to wrestle rival males off tree trunks.', 'Ancient oak woodlands and hedgerows across Europe', 'Herbivore - oak tree sap and decomposing dead wood', 'Near Threatened', 'Magpies, crows, tawny owls, and foxes', 'Their giant jaws look fierce but cannot bite humans hard because muscles are adapted for leverage!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🦌']
);
list.push(
  ['Dead Leaf Butterfly', 'Kallima inachus', 'The world champion of leaf camouflage', 'When its wings are closed, it is virtually indistinguishable from a dry brown dead leaf, complete with veins, mildew spots, and a leaf stalk!', 'Tropical rainforests from India to Japan', 'Frugivore - rotting peaches, fermenting sap, and dung', 'Least Concern', 'Birds, lizards, and mantises', 'When it opens its wings, it reveals a shocking explosion of bright royal blue and orange!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🍂'],
  ['Emerald Ash Borer', 'Agrilus planipennis', 'The jewel-green metallic wood-boring beetle', 'A slender jewel beetle with an iridescent emerald-green shell and copper belly. Larvae chew serpentine S-shaped feeding galleries under tree bark.', 'Native to East Asia; introduced across North American ash forests', 'Herbivore - inner bark and phloem of ash trees', 'Least Concern', 'Woodpeckers and specialized parasitoid wasps', 'Adults leave distinct D-shaped exit holes when they emerge from tree trunks!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '❇️'],
  ['Giant Water Bug', 'Lethocerus americanus', 'The formidable toe-biter that hunts baby turtles', 'Growing up to 4 inches long with raptorial pincers, this aquatic assassin injects digestive enzymes to liquefy minnows, frogs, and baby water snakes.', 'Freshwater ponds, slow streams, and marshes across North America', 'Carnivore - minnows, tadpoles, small turtles, and frogs', 'Least Concern', 'Herons, egrets, northern pike, and bass', 'Fathers carry hundreds of glued eggs on their backs until they hatch, fanning them with fresh water!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🌊'],
  ['Bombardier Beetle', 'Brachinus crepitans', 'The living chemical cannon that shoots boiling acid steam', 'When threatened, it mixes hydroquinone and hydrogen peroxide in an internal chamber to blast 212°F boiling chemical spray with loud popping sounds!', 'Riverbanks, floodplains, and damp fields of Europe and North America', 'Carnivore - small caterpillars, earthworms, and insect larvae', 'Least Concern', 'Toads and spiders (most flee after getting sprayed in the face!)', 'Can swivel its rear turret nozzle in almost 360 degrees to blast attackers in any direction!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '💥'],
  ['Madagascan Sunset Moth', 'Chrysiridia rhipheus', 'The most colorful day-flying moth in the world', 'Flies in bright tropical sunshine and was once thought to be a butterfly. Its rainbow wings flash fiery scarlet, emerald green, and deep violet reflections.', 'Forest canopies across the island of Madagascar', 'Herbivore (Nectarivore) - white and yellow tea tree flowers; caterpillars eat Omphalea leaves', 'Least Concern', 'Birds, geckos, and chameleons', 'The colors on its wings contain no pigment at all; they are created by optical interference of light on curved scales!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🌈'],
  ['Silkworm Moth', 'Bombyx mori', 'The ancient producer of shimmering royal silk', 'Completely domesticated by humans for over 5,000 years to produce silk fabric. Adult moths are fluffy white and can no longer fly or survive in the wild.', 'Mulberry orchards and silk farms worldwide (domesticated)', 'Caterpillars eat exclusively fresh mulberry tree leaves; adults do not eat', 'Domesticated', 'Rats, birds, and ants (in farm settings)', 'A single silkworm cocoon is spun from a continuous silk thread that can be over 3,000 feet long!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🧵'],
  ['Giant Malaysian Leaf Insect', 'Pulchriphyllium pulchrifolium', 'The fluttering emerald leaf with fake bite marks', 'Has an extraordinarily flattened green body complete with leaf veins and brown withered edges that look like insect bite marks. It rocks back and forth to simulate a leaf blowing in the wind.', 'Tropical rainforests of Malaysia and Indonesia', 'Herbivore - leaves of guava, mango, and oak trees', 'Least Concern', 'Tree lizards, monkeys, and jungle birds', 'Females can reproduce through parthenogenesis without mating when no males are nearby!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🍃'],
  ['Jewel Beetle', 'Chrysochroa fulgidissima', 'The iridescent living emerald of ancient temples', 'A dazzling beetle with glowing metallic green wings striped with purple-red racing lines. In ancient Japan, its shimmering wing cases were used to decorate the historic Tamamushi Shrine.', 'Warm forests of Japan, Korea, and Taiwan', 'Herbivore - leaves of cherry blossom, persimmon, and zelkova trees', 'Least Concern', 'Woodpeckers, flycatchers, and praying mantises', 'The wings retain their bright metallic luster even after hundreds of years without fading!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '✨'],
  ['Red Velvet Ant (Cow Killer)', 'Dasymutilla occidentalis', 'The fuzzy scarlet wasp with an agonizing sting', 'Despite its ant name, this is actually a wingless female solitary ground wasp covered in brilliant red and black velvet fur. Its squeaking stridulation warns enemies away.', 'Pastures, sandy fields, and open pine woods of North America', 'Adults sip nectar; larvae are parasitoids of bumblebee nests', 'Least Concern', 'Almost no predators; possesses ultra-tough flexible armor', 'Its flexible exoskeleton is so tough that entomologists struggle to pierce it with steel mounting pins!', 'https://images.unsplash.com/photo-1533230678098-904c6ca9b788?auto=format&fit=crop&w=800&q=80', '🔴'],
  ['Tarantula Hawk Wasp', 'Pepsis grossa', 'The bold blue-black hunter that takes on giant tarantulas', 'A massive 2-inch wasp with metallic blue-black body and bright fiery rust wings. Females seek out burrowing tarantulas, flip them onto their backs, and sting them into paralysis.', 'Deserts and grasslands of southwestern USA and Mexico', 'Adults feed on sweet milkweed nectar; larvae consume a paralyzed tarantula', 'Least Concern', 'Roadrunners and bullfrogs (few dare to tackle it)', 'Has the second most painful insect sting in the world, causing immediate electric paralysis for 3 minutes!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🦅'],
  ['Potter Wasp', 'Eumenes fraternus', 'The master clay architect that crafts ceramic mud pots', 'Females gather mud and water to sculpt miniature clay jugs that look just like human pottery jars on plant stems, stocking them with caterpillars for their larvae.', 'Gardens, forest edges, and meadows of eastern North America', 'Adults drink flower nectar; larvae feed on stored caterpillars', 'Least Concern', 'Parasitic cuckoo wasps and songbirds', 'Each mud pot is shaped with a refined flanged neck and sealed with a mud stopper!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🏺'],
  ['European Paper Wasp', 'Polistes dominula', 'The clever communal nest builder that crafts gray paper combs', 'Chews weathered wood and plant fibers, mixing them with saliva to create light, waterproof hexagonal paper nests under porch eaves and rock overhangs.', 'Meadows, gardens, and human structures across Europe and North America', 'Omnivore - caterpillars, flies, beetle larvae, and ripe nectar', 'Least Concern', 'Badgers, praying mantises, and bee-eaters', 'Individual paper wasps have unique facial markings that other wasps use to recognize them!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '📜'],
  ['Eastern Tiger Swallowtail', 'Papilio glaucus', 'The giant yellow butterfly that floats like a tiger kite', 'A large spectacular butterfly with bright yellow wings slashed with black tiger stripes. Caterpillars look like tiny green snakes complete with fake staring eye-spots!', 'Woodlands, parks, and riverside bottomlands of North America', 'Herbivore (Nectarivore) - lilac, wild cherry, and milkweed nectar', 'Least Concern', 'Dragonflies, songbirds, mantises, and crab spiders', 'When startled, the caterpillar extends orange forked stink-horns called osmeteria that smell like rancid cheese!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🐯'],
  ['Painted Lady Butterfly', 'Vanessa cardui', 'The cosmopolitan world wanderer found on every continent except Antarctica', 'The most widespread butterfly on Earth! They undertake immense multi-generational migrations crossing deserts, mountain ranges, and open oceans.', 'Open country, gardens, sand dunes, and mountains globally', 'Herbivore (Nectarivore) - thistles, asters, cosmos, and clover', 'Least Concern', 'Robber flies, spiders, wasps, and insect-eating birds', 'Can migrate at speeds of nearly 30 miles per hour and fly up to 1,000 miles in a few days!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🎨'],
  ['European Peacock Butterfly', 'Aglais io', 'The winged illusionist with glaring purple eye spots', 'When resting, its chocolate-brown undersides hide it completely. If a hungry bird approaches, it snaps its wings open to reveal four huge violet eye-spots while hissing loudly!', 'Gardens, pastures, and woodland clearings across Europe and temperate Asia', 'Herbivore (Nectarivore) - buddleia, dandelions, and clover; caterpillars eat stinging nettles', 'Least Concern', 'Blue tits, chaffinches, and spiders', 'Can rub its wing veins together to make an audible hissing sound that scares away mice and small birds!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '👁️'],
  ['Glasswing Butterfly', 'Greta oto', 'The magical fairy butterfly with crystal-clear invisible wings', 'The tissue between its wing veins is 100% transparent glass-like membrane, allowing light to pass straight through. When flying through rainforest shade, it is nearly invisible!', 'Tropical rainforests from Mexico to South America', 'Herbivore (Nectarivore) - tropical rainforest blossoms like lantana', 'Least Concern', 'Rufous-tailed jacamars and canopy flycatchers', 'Nanoscale pillar structures on its wings cancel light reflection, preventing glare just like high-tech camera lenses!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🪟'],
  ['Zebra Longwing Butterfly', 'Heliconius charithonia', 'The striped genius butterfly that eats nutritious pollen', 'Decorated in bold black wings with creamy yellow zebra stripes. Uniquely among butterflies, they collect and digest pollen grains, gaining proteins that let them live for 6 months!', 'Hardwood hammocks, edges, and gardens of Florida, Texas, and Central America', 'Herbivore - passionflower nectar and protein-rich pollen', 'Least Concern', 'Anoles, tree frogs, and dragonflies', 'Roost together in communal sleeping clusters of up to 60 individuals every evening on the same vine!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🦓'],
  ['Queen Alexandra\'s Birdwing', 'Ornithoptera alexandrae', 'The largest butterfly on planet Earth', 'With a gigantic wingspan reaching up to 11 inches across, females are as big as a dinner plate! They soar majestically through the high rainforest canopy of Papua New Guinea.', 'Lowland coastal rainforests of Oro Province, Papua New Guinea', 'Herbivore (Nectarivore) - high canopy flowers; caterpillars eat toxic Aristolochia vines', 'Endangered', 'High canopy birds of prey, monitor lizards, and spiders', 'First specimen collected in 1906 had to be brought down by a naturalist using a small shotgun!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '👑'],
  ['Postman Butterfly', 'Heliconius melpomene', 'The bright red and black mimic of Amazonian vines', 'Famous for its velvety black wings with vivid scarlet bands and white spots. It shares identical warning patterns with other toxic butterflies in a classic example of Müllerian mimicry.', 'Tropical rainforest clearings and river edges of South America', 'Herbivore - passionflower nectar and digested pollen grains', 'Least Concern', 'Jacamars and arboreal lizards', 'Can remember the exact locations of their favorite flowers in a daily foraging trap-line route!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '📮'],
  ['Giant Owl Butterfly', 'Caligo memnon', 'The twilight glider with massive fake owl eyes on its wings', 'Flies at dawn and dusk through Central American jungles. Each hindwing sports a giant yellow-ringed black spot that perfectly resembles the eye of a hungry owl staring from a branch.', 'Lowland rainforests and banana plantations from Mexico to Brazil', 'Frugivore - fermenting bananas, crushed figs, and tree sap', 'Least Concern', 'Forest flycatchers, trogons, and coatis', 'Caterpillars possess small horns on their heads and can grow nearly 6 inches long!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🦉'],
  ['Death\'s-Head Hawkmoth', 'Acherontia atropos', 'The squeaking honey thief with a human skull on its back', 'Instantly recognized by the eerie skull-shaped marking on its thorax. It sneaks into honeybee hives unharmed by mimicking bee scent, sipping honey and squeaking loudly through its mouth!', 'Farmland, gardens, and scrublands across Europe and Africa', 'Herbivore - honey from bee hives and sweet tree sap; caterpillars eat potato leaves', 'Least Concern', 'Barn owls, bats, and nightjars', 'Is one of the very few moths capable of emitting a loud squeak by forcing air through its pharynx!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '💀'],
  ['Hummingbird Hawk-Moth', 'Macroglossum stellatarum', 'The supersonic hovering moth mistaken for a bird', 'Beats its wings at 85 beats per second, hovering steadily in front of flowers and unrolling a long straw-like proboscis to drink nectar just like a real hummingbird!', 'Gardens, meadows, and sea cliffs across Europe, Asia, and North Africa', 'Herbivore (Nectarivore) - honeysuckle, lavender, and jasmine blossoms', 'Least Concern', 'Spiders, swifts, and flycatchers', 'Has exceptional vision and can learn to associate specific colors with sweet nectar rewards!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🌺'],
  ['Rosy Maple Moth', 'Dryocampa rubicunda', 'The adorable pink and lemonade-yellow woolly moth', 'Looks like a plush toy made of cotton candy, with fluffy woolly pink and yellow fur and feathery antennae. Adults do not eat at all and spend their brief lives searching for mates.', 'Deciduous maple forests across eastern North America', 'Adults do not feed; caterpillars feed on leaves of red, sugar, and silver maples', 'Least Concern', 'Blue jays, chickadees, and tufted titmice', 'Their thick woolen fuzz protects their sensory organs and keeps them warm during cool nights!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🍧'],
  ['Cecropia Moth', 'Hyalophora cecropia', 'North America\'s largest native silk moth', 'Boasting an astonishing wingspan of up to 6 inches, this velvety giant features reddish-brown wings adorned with crescent-shaped moon spots and fur-lined legs.', 'Hardwood forests and urban parks of North America', 'Adults do not feed; caterpillars eat birch, cherry, and apple leaves', 'Least Concern', 'Screech owls, bats, and parasitic ichneumon wasps', 'Caterpillars start out black and transform into neon green giants covered in multi-colored knobby spikes!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🦋'],
  ['Polyphemus Moth', 'Antheraea polyphemus', 'The giant moth named after the mythological cyclops', 'Named after the Greek cyclops Polyphemus because each hindwing features a colossal blue-and-yellow eye-spot that startles woodpeckers and bats.', 'Hardwood deciduous forests, orchards, and wetlands across North America', 'Adults do not feed; caterpillars consume oak, birch, and willow leaves', 'Least Concern', 'Raccoons, bats, and woodland songbirds', 'A single caterpillar can eat 86,000 times its birth weight in foliage in less than two months!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '👁️']
);
list.push(
  ['Hercules Moth', 'Coscinocera hercules', 'The largest moth in the world by wing surface area', 'Native to the tropical rainforests of northern Australia and New Guinea. With a wing surface area of nearly 46 square inches, it is an absolute giant of the insect world!', 'Tropical rainforests of northern Queensland and New Guinea', 'Adults do not feed; caterpillars eat leaves of bleeding heart and cheese trees', 'Least Concern', 'Owls, bats, and tree pythons', 'Females release powerful pheromones that male moths can smell from over a mile away using feathery antennae!', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80', '🏆'],
  ['Giraffe Weevil', 'Trachelophorus giraffa', 'The bizarre red beetle with an impossibly long neck', 'Found exclusively on the island of Madagascar. Males possess an extraordinarily elongated neck up to three times longer than their body, used for wrestling rivals!', 'Tropical rainforest canopies of Madagascar', 'Herbivore - leaves of the Dichaetanthera tree', 'Least Concern', 'Chameleons, geckos, and insectivorous birds', 'Females use their shorter necks to fold and roll a single leaf into a tight cigar-shaped tube to lay an egg inside!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🦒'],
  ['Acorn Weevil', 'Curculio glandium', 'The tiny beetle with a snout longer than its entire body', 'A cute round beetle equipped with an impossibly slender curved snout like a dentist drill, used to bore deep into hard oak acorns to deposit eggs.', 'Oak woodlands and hedgerows across Europe', 'Herbivore - interior nut meat of oak acorns', 'Least Concern', 'Woodland birds, wood mice, and ground beetles', 'The microscopic serrated teeth at the very tip of its snout can drill through rock-hard acorn shells in hours!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🌰'],
  ['Japanese Beetle', 'Popillia japonica', 'The metallic copper-and-green scarab of summer gardens', 'A shiny scarab beetle featuring iridescent green heads and metallic copper wing covers. In groups, they skeletonize leaves, leaving behind delicate lace patterns.', 'Gardens, farms, and turfgrass in East Asia and North America', 'Herbivore - leaves, flowers, and fruit of over 300 plant species', 'Least Concern', 'Starlings, moles, skunks, and assassin bugs', 'Adults release an aggregation pheromone that calls hundreds of other beetles to the same branch!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🪲'],
  ['Red Imported Fire Ant', 'Solenopsis invicta', 'The resilient rafter ant that builds living unsinkable boats', 'Infamous for their fiery burning stings. During heavy floods, hundreds of thousands of ants link legs and mandibles to weave a living floating waterproof raft that survives for weeks!', 'Grasslands, lawns, and agricultural fields globally', 'Omnivore - seeds, young plants, insects, and small vertebrates', 'Least Concern', 'Phorid flies and armadillos', 'Their living rafts can assemble in less than 2 minutes when floodwaters rise!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🚣'],
  ['Weaver Ant', 'Oecophylla smaragdina', 'The green tree architects that glue leaves with silk-spinning babies', 'Builds lush hanging leaf nests in tropical trees. Chains of worker ants pull heavy leaves together with their jaws, while other workers hold silk-spinning larvae like glue guns!', 'Tropical forests and orchards of Southeast Asia and northern Australia', 'Carnivore - caterpillars, beetles, flies, and plant-sucking bugs', 'Least Concern', 'Tree monitor lizards and specialized jumping spiders', 'Use their own baby larvae as living glue sticks to stitch leaves together with waterproof silk!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🍃'],
  ['Honeypot Ant', 'Myrmecocystus mexicanus', 'The living golden amber storage barrels of desert nests', 'Certain specialized worker ants called repletes are stuffed with flower nectar and aphid honeydew until their abdomens swell as big as round golden glass marbles!', 'Arid deserts and savannas of southwestern North America and Mexico', 'Herbivore - sweet floral nectar and insect honeydew', 'Least Concern', 'Coyotes, badgers, and rival ant colonies', 'During severe desert droughts, other worker ants stroke them with antennae to drink stored honey drops!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🍯'],
  ['Trap-Jaw Ant', 'Odontomachus bauri', 'The lightning jaws that snap faster than a bullet', 'Has spring-loaded mandibles that snap shut at speeds of 140 miles per hour—one of the fastest predatory strikes on planet Earth! They can even snap them against the ground to launch themselves backward into the air.', 'Tropical and subtropical forest floors worldwide', 'Carnivore - termites, springtails, and small crickets', 'Least Concern', 'Horned lizards, toads, and blind snakes', 'Can snap their jaws against the floor to rocket themselves 15 inches into the air to escape predators!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '⚡'],
  ['Driver Ant (Siafu)', 'Dorylus molestus', 'The fearsome nomadic legion of the African wilderness', 'A massive African safari ant that marches in unstoppable predatory columns up to 20 million strong. Their huge jaws are so powerful they can hold wounds shut like natural surgical sutures!', 'Dense forests and savannahs of Sub-Saharan Africa', 'Carnivore - earthworms, scorpions, lizards, and any trapped small animals', 'Least Concern', 'Chimpanzees (using twigs to fish for them) and baboons', 'Local people historically used driver ant soldiers as natural surgical stitches to close skin cuts!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🩹'],
  ['Red Harvester Ant', 'Pogonomyrmex barbatus', 'The desert granary builders that collect wildflower seeds', 'Clears wide circular dirt landing pads around their nest entrances and forages for grass seeds, storing them in vast cool underground storage granaries.', 'Arid grasslands and scrublands of southwestern USA and Mexico', 'Herbivore - grass and wildflower seeds; occasional dead insects', 'Least Concern', 'Texas horned lizards (whose specialized digestive systems are immune to ant venom!)', 'Worker ants groom seeds to prevent them from sprouting inside underground storage vaults!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🌾'],
  ['Golden Tortoise Beetle', 'Charidotella sexpunctata', 'The shimmering gold coin beetle that changes color when romantic', 'Can change its shell color from brilliant metallic 24-karat gold to reddish-bronze with black spots in minutes by altering moisture levels in its transparent shell layers!', 'Meadows, roadsides, and gardens of North America', 'Herbivore - leaves of morning glories and sweet potato vines', 'Least Concern', 'Damsel bugs, assassin bugs, and spiders', 'Shifts to a bright red color when agitated or mating, like a living mood ring!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🪙'],
  ['Eyed Click Beetle', 'Alaus oculatus', 'The somersaulting gymnast with giant false eyes', 'Features two huge velvet black eye-spots rimmed with white on its neck. When flipped on its back, it snaps an internal spine hinge with a loud CLICK that launches it 6 inches into the air!', 'Deciduous hardwood forests and rotting logs across North America', 'Carnivore as larvae (chews through woodboring grubs); adults feed on nectar', 'Least Concern', 'Woodpeckers, crows, and raccoons', 'The loud click and acrobatic somersault startlingly scares predators and flips the beetle upright!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🤸'],
  ['Sacred Dung Beetle', 'Scarabaeus sacer', 'The celestial star navigator of ancient Egyptian lore', 'Revered in ancient Egypt as a symbol of the sun god Ra. They roll dung balls across desert sands in straight lines by orienting themselves using the light of the Milky Way!', 'Mediterranean sand dunes, savannas, and dry grasslands', 'Herbivore (Coprophage) - herbivore dung and nutrient-rich droppings', 'Least Concern', 'Jackals, crows, owls, and monitor lizards', 'Is the first known animal proven to navigate using the faint light of the Milky Way galaxy!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '🌌'],
  ['Devil\'s Coach Horse Beetle', 'Ocypus olens', 'The scorpion-posing night hunter of European gardens', 'A fierce black rove beetle with short wing covers. When threatened, it arches its tail over its head like a stinging scorpion and opens powerful jaws while emitting a foul odor!', 'Woodlands, hedgerows, and gardens across Europe', 'Carnivore - woodlice, slugs, snails, caterpillars, and worms', 'Least Concern', 'Hedgehogs, toads, and owls', 'Despite looking like a deadly scorpion, it has no stinger at all and relies purely on bluffing!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🦂'],
  ['Spanish Fly (Blister Beetle)', 'Lytta vesicatoria', 'The brilliant metallic green beetle with chemical defense', 'A shimmering metallic green beetle that produces cantharidin, a potent blister-causing chemical defense that prevents birds and mammals from eating it.', 'Open woodlands and scrub of southern Europe and Central Asia', 'Herbivore - leaves of ash, lilac, and privet trees', 'Least Concern', 'Very few predators due to painful chemical blistering', 'Historically used in ancient medicines and pigments for its emerald coloration!', 'https://images.unsplash.com/photo-1549488497-6a1a1f0a512d?auto=format&fit=crop&w=800&q=80', '🧪'],
  ['Whirligig Beetle', 'Gyrinus natator', 'The split-eyed speedboater of freshwater ponds', 'Skims across the water surface in wild dizzying circles at 40 body lengths per second. Its compound eyes are split into two halves: one half looks down into the water, while the other looks up at the sky!', 'Quiet streams, ponds, and lake margins across Europe and North America', 'Carnivore - dead or struggling insects trapped on the water surface', 'Least Concern', 'Bass, trout, and green herons', 'Has two pairs of eyes: one pair watches for fish below while the other watches for birds above!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '👀'],
  ['Great Diving Beetle', 'Dytiscus marginalis', 'The submarine hunter that breathes through an air scuba tank', 'One of the largest aquatic beetles. It traps an air bubble beneath its wing covers before diving, which acts like a scuba tank so it can hunt underwater for hours!', 'Deep, weed-choked freshwater ponds and canals across Europe', 'Carnivore - tadpoles, water insects, newts, and small fish', 'Least Concern', 'Herons, pike, and otters', 'Larvae are nicknamed water tigers because they inject digestive juices directly into prey with curved hollow fangs!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '🤿'],
  ['Common Water Strider', 'Aquarius remigis', 'The miracle surface walker that glides on water tension', 'Walks effortlessly across water surfaces without sinking! Microscopic water-repellent hairs on its long legs trap tiny cushions of air that ride on surface tension.', 'Ponds, lakes, and quiet river pools across North America', 'Carnivore - drowned gnats, flies, and fallen caterpillars', 'Least Concern', 'Trout, frogs, and diving beetles', 'Can sprint across the water surface at an astonishing speed of 3 feet per second!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '⛸️'],
  ['Backswimmer Bug', 'Notonecta glauca', 'The upside-down aquatic oarsman with a painful bite', 'Swims upside-down beneath the water surface using its extra-long fringed hind legs like rowboat oars. It can pierce fingers with a bite that feels like a wasp sting!', 'Ponds, ditches, and slow streams across Europe', 'Carnivore - mosquito larvae, tadpoles, and water fleas', 'Least Concern', 'Pike, perch, and wading birds', 'Its silvery underbelly acts as countershading, making it invisible to fish swimming below!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🛶'],
  ['Wheel Bug', 'Arilus cristatus', 'The prehistoric assassin with a cogwheel crest on its back', 'North America\'s largest assassin bug, recognized by a prominent cogwheel crest on its thorax. It stalks caterpillars slowly, then plunges its dagger-like beak to inject paralyzing saliva.', 'Forest edges, orchards, and urban gardens across North America', 'Carnivore - caterpillars, Japanese beetles, sawflies, and stink bugs', 'Least Concern', 'Blue jays, crows, and praying mantises', 'Its prominent armor crest looks exactly like a steel mechanical cogwheel from an old clock!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '⚙️'],
  ['Jagged Ambush Bug', 'Phymata fasciata', 'The camouflage master hidden inside yellow goldenrod flowers', 'Has thickened front claws that look like crab claws and a bumpy yellow-and-green body. It sits motionless inside yellow flowers, ambushing insects ten times its size!', 'Sunny wildflower meadows and goldenrod fields of North America', 'Carnivore - bees, butterflies, moths, and syrphid flies', 'Least Concern', 'Crab spiders, dragonflies, and meadowlarks', 'Can overpower honeybees and bumblebees that are much larger and heavier than itself!', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', '🌼'],
  ['Meadow Spittlebug', 'Philaenus spumarius', 'The bubble bath builder with world-record jumping power', 'Nymphs produce protective white frothy bubbles called cuckoo spit on plant stems. Adults can jump over 2 feet into the air, withstanding over 400 times the acceleration of gravity!', 'Fields, meadows, and roadsides worldwide', 'Herbivore - plant sap from clovers, grasses, and wildflowers', 'Least Concern', 'Ladybug larvae, spiders, and meadow birds', 'Relative to body size, spittlebugs jump higher and with more force than fleas!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🫧'],
  ['Thorn Bug Treehopper', 'Umbonia crassicornis', 'The colorful treehopper disguised as a prickly rose thorn', 'Has an enormous pointed horn that mimics sharp tree thorns, painted in bright yellow, red, and green stripes. Mother thorn bugs communicate by vibrating plant stems with song waves!', 'Subtropical hammocks, gardens, and fruit trees of Florida and Central America', 'Herbivore - sap from acacia, hibiscus, and wild tamarind', 'Least Concern', 'Jumping spiders, anoles, and assassin bugs', 'Mothers fiercely guard their clusters of nymphs from predators, buzzing loudly and flicking their wings!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🌹'],
  ['Spotted Lanternfly', 'Lycorma delicatula', 'The polka-dotted planthopper with crimson underwings', 'A planthopper with light brown front wings covered in black spots and vivid scarlet hind wings. They produce sweet honeydew fluid that coats tree trunks.', 'Native to China; introduced to eastern North America', 'Herbivore - sap from tree of heaven, grapevines, and walnuts', 'Least Concern', 'Wheel bugs, praying mantises, and predatory wasps', 'Despite having colorful wings, they hop with powerful spring legs rather than flying long distances!', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=800&q=80', '🔴'],
  ['Green Lacewing', 'Chrysoperla carnea', 'The fairy-winged gardener with glowing golden eyes', 'Has delicate transparent net-veined wings, a lime-green slender body, and brilliant golden eyes. Larvae are voracious pest-eaters nicknamed aphid lions!', 'Gardens, meadows, and orchards worldwide', 'Larvae are carnivores (aphids and mites); adults feed on nectar and pollen', 'Least Concern', 'Bats, spiders, and robber flies', 'Adults can hear the high-frequency echolocation sonar of bats and instantly drop out of the air to safety!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🧚']
);
list.push(
  ['European Antlion', 'Myrmeleon formicarius', 'The sand-pit trap builder with terrifying curved jaws', 'Larvae dig conical sand pits in dry soil and bury themselves at the bottom with only their curved fangs exposed. When an ant slips on the loose sand, the antlion flings dirt to pull it down!', 'Sandy pine forests, dunes, and dry riverbanks across Europe', 'Carnivore - ants, small spiders, and crawling beetles', 'Least Concern', 'Birds, lizards, and ground beetles', 'Can only walk backwards; they cannot walk forward at all as larvae!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '⏳'],
  ['Eastern Dobsonfly', 'Corydalus cornutus', 'The river monster with curved two-inch tusks', 'Adult males possess massive sickle-shaped tusks that look terrifying but are harmless to humans. Aquatic larvae, called hellgrammites, live under river boulders for up to 3 years.', 'Clean, fast-flowing rocky rivers across North America', 'Adults rarely feed; larvae are fierce carnivores eating minnows and nymphs', 'Least Concern', 'Smallmouth bass, trout, raccoons, and herons', 'Hellgrammites are one of the most prized live baits for river bass fishermen!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '👹'],
  ['Snakefly', 'Raphidia ophiopsis', 'The long-necked predatory flyer of coniferous woods', 'Named for its extraordinarily elongated neck and mobile head that strikes at prey with the lightning precision of a striking cobra!', 'Pine and oak forests across Europe and northern Asia', 'Carnivore - aphids, bark lice, caterpillars, and insect eggs', 'Least Concern', 'Warblers, nuthatches, and spiders', 'Can raise its head high in the air and strike at prey just like a miniature hooded cobra!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🐍'],
  ['Common Scorpionfly', 'Panorpa communis', 'The harmless forest dweller with a scorpion-tail bluff', 'Males possess an enlarged genital capsule at the end of their abdomen that curls upward like a deadly scorpion stinger, but it is 100% harmless!', 'Damp hedgerows, nettle beds, and forest edges of Europe', 'Carnivore / Scavenger - dead insects and fruit sap stolen from spider webs', 'Least Concern', 'Robber flies, dragonflies, and thrushes', 'Courting males bring a wrapped package of food as an edible wedding gift to woo females!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🦂'],
  ['Green Drake Mayfly', 'Ephemera danica', 'The one-day winged marvel that dances over rivers', 'Spends two years burrowed in clean river silt, then emerges with millions of others for a single 24-hour frenzy of flying and mating, living without a mouth or digestive system!', 'Clean gravel rivers, chalk streams, and lakes of Europe', 'Does not feed as an adult; nymphs eat organic river debris and algae', 'Least Concern', 'Brown trout, grayling, swifts, and bats', 'Is the only insect order that molts once more after already gaining functional flying wings!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🪰'],
  ['Golden Stonefly', 'Hesperoperla pacifica', 'The clean water sentinel of cold rushing rapids', 'Lives in pristine, oxygen-rich mountain rapids. Their presence in a stream is the golden standard proof that the water is 100% pure and unpolluted.', 'Cold mountain rivers and cascades of western North America', 'Carnivore as nymphs (mayfly nymphs and blackfly larvae); adults feed on algae', 'Least Concern', 'Rainbow trout, dippers (water ouzels), and kingfishers', 'Nymphs do push-ups on underwater stones to increase oxygen flow across their gills!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🌊'],
  ['Northern Caddisfly', 'Limnephilus flavicornis', 'The underwater stonemason that builds jewelry cases', 'Aquatic larvae spin silk tubes and glue together tiny river pebbles, snail shells, and sand grains into mobile armored mobile sleeping bags!', 'Ponds, ditches, and slow streams across Europe', 'Herbivore / Detritivore - decaying leaves, moss, and algae', 'Least Concern', 'Trout, dragonflies, and mallard ducks', 'French artists famously gave them gold flakes and turquoise beads, and the larvae built real jewelry!', 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80', '💎'],
  ['Field Cricket', 'Gryllus bimaculatus', 'The temperature-telling musical fiddler of summer nights', 'Rub their front wings together to produce cheerful chirping serenades. You can calculate the outdoor temperature by counting the number of chirps in 15 seconds and adding 40!', 'Pastures, sunny meadows, and roadsides across Europe and Asia', 'Omnivore - seeds, seedlings, decaying fruit, and dead insects', 'Least Concern', 'Shrews, hedgehogs, kestrels, and wolf spiders', 'Dolbear\'s Law states you can accurately measure Fahrenheit temperature using a cricket\'s chirp rate!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🎻'],
  ['European Mole Cricket', 'Gryllotalpa gryllotalpa', 'The subterranean burrower with mole-like spade paws', 'Equipped with giant shovel-like front claws just like a mammalian mole! It constructs trumpet-shaped underground tunnels that amplify its singing song.', 'Moist sandy soil, floodplains, and gardens across Europe', 'Omnivore - earthworms, beetle grubs, and plant roots', 'Least Concern', 'Barn owls, badgers, foxes, and storks', 'Its horn-shaped underground acoustic burrow amplifies its chirp so loud it can be heard 2,000 feet away!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '⛏️'],
  ['Jerusalem Cricket', 'Stenopelmatus fuscus', 'The giant baby-headed potato bug that drums on soil', 'A heavy, wingless cricket with a bulbous smooth head that looks surprisingly like a human infant. It communicates by thumping its abdomen against the soil!', 'Semi-arid sandy fields, chaparral, and gardens of western North America', 'Omnivore - plant roots, decaying tubers, and dead insects', 'Least Concern', 'Coyotes, screech owls, and skunks', 'Despite its common name, it is not from Jerusalem and does not eat only potatoes!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🥔'],
  ['Camel Cricket', 'Ceuthophilus maculatus', 'The humpbacked spider cricket that leaps 3 feet into the air', 'Has an arched humpback, extra-long spindly legs, and no wings. When alarmed in dark cellars or caves, it jumps directly toward the intruder to startle them!', 'Caves, hollow trees, leaf litter, and damp basements of North America', 'Omnivore - decaying fungi, carpet fibers, and dead insects', 'Least Concern', 'Salamanders, mice, bats, and wolf spiders', 'Has no sound-producing organs or ears, navigating purely through long sensitive antennae!', 'https://images.unsplash.com/photo-1568480541687-16c2f73eea4c?auto=format&fit=crop&w=800&q=80', '🐪'],
  ['Desert Locust', 'Schistocerca gregaria', 'The swarming cloud that can darken the midday sky', 'Normally solitary grasshoppers, but when crowded, serotonin triggers a complete physical transformation into gregarious swarms of billions that can eat entire harvests in hours!', 'Deserts and scrublands from North Africa through the Middle East to India', 'Herbivore - grains, grasses, leaves, fruit, and crops', 'Least Concern', 'Kestrels, buzzards, desert foxes, and storks', 'A single large swarm can cover 460 square miles and consume 423 million pounds of plants every day!', 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?auto=format&fit=crop&w=800&q=80', '🌾'],
  ['Great Green Bush Cricket', 'Tettigonia viridissima', 'The giant singing emerald giant of European hedgerows', 'One of the largest insects in Europe, with long thread-like antennae and a vibrant apple-green body. Males sing a loud piercing song on warm summer afternoons.', 'Warm scrublands, meadows, and gardens across Europe and Central Asia', 'Omnivore - caterpillars, flies, aphids, and tender dandelion leaves', 'Least Concern', 'Buzzards, kestrels, hedgehogs, and bats', 'Females possess a massive sword-like egg-laying organ (ovipositor) longer than their body!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '⚔️'],
  ['Little Barrier Island Giant Weta', 'Deinacrida heteracantha', 'The heavyweight dinosaur bug as heavy as a sparrow', 'Found only on protected islands in New Zealand. Weighing up to 2.5 ounces, it is heavier than a sparrow and is one of the heaviest insects in the world!', 'Native forest canopies of Little Barrier Island, New Zealand', 'Herbivore - leaves, fungi, flowers, and native berries', 'Vulnerable', 'Introduced rats and native tuataras', 'Filled the ecological niche of mice and rats in New Zealand before land mammals arrived!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🇳🇿'],
  ['Common Earwig', 'Forficula auricularia', 'The devoted mother insect with tail pincers', 'Equipped with a pair of curved cerci (pincers) on its tail used for defense and unfolding wings. Mother earwigs are famously devoted parents that care for and clean their eggs.', 'Gardens, compost piles, and woodlands across Europe and North America', 'Omnivore - aphids, insect eggs, decaying organic matter, and flower petals', 'Least Concern', 'Robins, starlings, toads, and centipedes', 'The ancient myth that they crawl into human ears to lay eggs is 100% false folklore!', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', '✂️'],
  ['Common Silverfish', 'Lepisma saccharinum', 'The shimmering ancient fish-like creature of dark corners', 'A wingless, silver-scaled insect that moves with a wriggling fish-like glide. It has survived almost unchanged for over 400 million years, older than dinosaurs!', 'Damp basements, bathrooms, and libraries worldwide', 'Herbivore - starch, sugar, bookbinding glue, and paper fibers', 'Least Concern', 'House centipedes, earwigs, and spiders', 'Can survive for up to an entire year without eating a single crumb of food!', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80', '🐟'],
  ['Formosan Subterranean Termite', 'Coptotermes formosanus', 'The wood-chewing civil engineers of massive underground nests', 'A single super-colony can contain several million termites and forage across a 300-foot territory, digesting tough cellulose using symbiotic gut microbes.', 'Subtropical soils and wooden structures worldwide', 'Herbivore (Xylophage) - structural wood, fallen logs, and plant roots', 'Least Concern', 'Anteaters, predatory ants, and woodpeckers', 'Their digestive tract harbors specialized bacteria that can break down wood into edible sugars!', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80', '🪵'],
  ['Marmalade Hoverfly', 'Episyrphus balteatus', 'The harmless wasp mimic that hovers like a drone', 'A master imitator with black and orange wasp stripes that tricks birds into leaving it alone. It can hover completely motionless in midair and fly backwards!', 'Gardens, crop fields, and meadows across Europe and Asia', 'Adults drink nectar and pollen; larvae eat hundreds of garden aphids', 'Least Concern', 'Swallows, flycatchers, and crab spiders', 'Migrates hundreds of miles across the English Channel and mountain ranges every year!', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', '🚁'],
  ['Red-Footed Cannibalfly (Robber Fly)', 'Promachus rufipes', 'The aerial highwayman that ambushes hornets mid-flight', 'A giant fuzzy robber fly that intercepts flying bees, wasps, and beetles in midair, wrapping them in spiny legs and injecting paralyzing saliva before landing.', 'Sunny fields, prairie edges, and pastures of North America', 'Carnivore - honeybees, bumblebees, grasshoppers, and cicadas', 'Least Concern', 'Scissor-tailed flycatchers, kingbirds, and kestrels', 'Can kill prey that is significantly larger and heavier than itself while flying at full speed!', 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80', '🥷']
);

const mapped = list.map((s, i) => ({
  id: 'insect-' + (i + 1),
  name: s[0],
  scientific: s[1],
  category: 'insects',
  tagline: s[2],
  description: s[3],
  habitat: s[4],
  diet: s[5],
  endangered: s[6],
  predators: s[7],
  funFact: s[8],
  image: s[9],
  emoji: s[10]
}));

const outPath = path.join(__dirname, '..', 'data', 'insects.js');
const js = '// 94 Insects Data File\nwindow.INSECTS_DATA = ' + JSON.stringify(mapped, null, 2) + ';\n';
fs.writeFileSync(outPath, js, 'utf8');
console.log('Successfully wrote data/insects.js with ' + mapped.length + ' species!');
