const fs = require('fs');
const path = require('path');

const { US_STATE_BIRDS_RAW, wikiImg } = require('../data/raw_state_birds');
const { COUNTRY_BIRDS_RAW } = require('../data/raw_country_birds');
const { MORE_COUNTRIES_RAW } = require('../data/raw_country_birds_part2');
const { FINAL_COUNTRIES_RAW } = require('../data/raw_country_birds_part3');

// Remaining nations to reach all 195+ UN recognized countries
const REMAINING_NATIONS = [
  {
    country: "Benin",
    code: "BJ",
    continent: "Africa",
    flag: "🇧🇯",
    name: "Red-Billed Firefinch",
    scientific: "Lagonosticta senegala",
    tagline: "The ruby-red garden visitor of Dahomey palaces",
    description: "The cheerful scarlet songbird of Benin! With bright red plumage and a bright pink bill with black center, it flits playfully around traditional earthen homesteads in Porto-Novo and Cotonou.",
    habitat: "Savannah grasslands, village gardens, and river valleys",
    diet: "Granivore - wild grass seeds and small termites",
    endangered: "Least Concern",
    predators: "Village weaver parasites and domestic cats",
    funFact: "Firefinches are so comfortable around people in West Africa that they regularly hop right through open kitchen doorways for crumbs!",
    image: wikiImg("thumb/9/94/Lagonosticta_senegala_male_Senegal.jpg/500px-Lagonosticta_senegala_male_Senegal.jpg")
  },
  {
    country: "Burkina Faso",
    code: "BF",
    continent: "Africa",
    flag: "🇧🇫",
    name: "Abyssinian Roller",
    scientific: "Coracias abyssinicus",
    tagline: "The long-tailed turquoise jewel of the Sahel",
    description: "The stunning emblem of Burkina Faso's savannah skies! Boasting brilliant sky-blue underparts, a brownish mantle, and two elongated wispy tail streamers that dance in the hot desert wind.",
    habitat: "Dry Sahelian savannas, open thorn scrub, and farmlands",
    diet: "Grasshoppers, beetles, scorpions, and small lizards",
    endangered: "Least Concern",
    predators: "Raptors",
    funFact: "They are frequently seen following savanna bushfires to snatch fleeing insects escaping the smoke!",
    image: wikiImg("thumb/1/14/Coracias_abyssinicus_Keulemans.jpg/500px-Coracias_abyssinicus_Keulemans.jpg")
  },
  {
    country: "Burundi",
    code: "BI",
    continent: "Africa",
    flag: "🇧🇮",
    name: "Crowned Crane",
    scientific: "Balearica regulorum",
    tagline: "The golden-crested dancer of Lake Tanganyika shores",
    description: "The iconic royal bird of Burundi! Striding majestically along the northern shores of Lake Tanganyika, its stiff golden crown shines in the equatorial sun as pairs perform synchronized leaping dances.",
    habitat: "Lake Tanganyika marshes, Rusizi River floodplains, and wet meadows",
    diet: "Seeds, grass stems, aquatic frogs, and insects",
    endangered: "Endangered",
    predators: "Leopards and pythons",
    funFact: "Burundi's Rusizi National Park provides a critical protected wetland sanctuary where these cranes gather in family flocks!",
    image: wikiImg("thumb/5/5e/Grey_crowned_crane_%28Balearica_regulorum%29_2.jpg/500px-Grey_crowned_crane_%28Balearica_regulorum%29_2.jpg")
  },
  {
    country: "Cabo Verde",
    code: "CV",
    continent: "Africa",
    flag: "🇨🇻",
    name: "Cape Verde Warbler (Passarinha)",
    scientific: "Acrocephalus brevipennis",
    tagline: "The melodious cane-dweller of Atlantic volcanic isles",
    description: "The endemic pride of Cabo Verde! Known locally in Crioulo as 'Passarinha.' Found only on the islands of Santiago, Fogo, and São Nicolau, singing a liquid, melodious song among green mountain ribeiras.",
    habitat: "Mountain valleys, sugarcane valleys, reedbeds, and coffee terraces",
    diet: "Insectivore - caterpillars, aphids, wasps, and spiders",
    endangered: "Endangered (Endemic to Cabo Verde)",
    predators: "Invasive feral cats and black rats",
    funFact: "Once feared extinct in the 20th century, passionate island surveys rediscovered breeding populations in mist-veiled mountain ravines!",
    image: wikiImg("thumb/5/5a/Acrocephalus_brevipennis_Keulemans.jpg/500px-Acrocephalus_brevipennis_Keulemans.jpg")
  },
  {
    country: "Central African Republic",
    code: "CF",
    continent: "Africa",
    flag: "🇨🇫",
    name: "African Grey Parrot",
    scientific: "Psittacus erithacus",
    tagline: "The brilliant genius of the Dzanga-Sangha rainforest canopy",
    description: "The cultural symbol of the Congo Basin in Central African Republic! Famous as the most intelligent parrot on planet Earth, capable of complex problem-solving and mimicking hundreds of rainforest sounds and animal voices.",
    habitat: "Pristine tropical rainforests of Dzanga-Ndoki and river clearings (bais)",
    diet: "Frugivore - oil palm nuts, wild figs, seeds, and mineral salts from forest clearings",
    endangered: "Endangered",
    predators: "African crowned eagles and leopards",
    funFact: "Flocks of hundreds of African Grey Parrots gather daily at Dzanga Bai ('The Village of Elephants') in CAR to drink mineral-rich mud!",
    image: wikiImg("thumb/7/73/Psittacus_erithacus_-perching_on_branch-8.jpg/500px-Psittacus_erithacus_-perching_on_branch-8.jpg")
  },
  {
    country: "Chad",
    code: "TD",
    continent: "Africa",
    flag: "🇹🇩",
    name: "Ostrich (North African Ostrich)",
    scientific: "Struthio camelus camelus",
    tagline: "The red-necked giant runner of the Ennedi plateau",
    description: "The grandest bird of Chad! The red-necked North African ostrich is the largest bird on Earth, standing up to 9 feet tall with pinkish-red neck skin. It sprints across the striking red sandstone arches of the Ennedi Plateau.",
    habitat: "Semi-desert plains, Sahel scrub, and the Ennedi sandstone massif",
    diet: "Seeds, shrubs, succulent desert plants, locusts, and lizards",
    endangered: "Critically Endangered in the wild",
    predators: "Cheetahs and hyenas",
    funFact: "An ostrich can run at sustained speeds of 43 mph, covering 16 feet in a single bounding stride!",
    image: wikiImg("thumb/e/ed/Struthio_camelus_camelus_male.jpg/500px-Struthio_camelus_camelus_male.jpg")
  },
  {
    country: "Comoros",
    code: "KM",
    continent: "Africa",
    flag: "🇰🇲",
    name: "Comoro Blue Pigeon",
    scientific: "Alectroenas sganzini",
    tagline: "The cobalt-plumed dove of Mount Karthala volcano",
    description: "The national bird of the Comoros! A gorgeous fruit pigeon with silver-gray neck feathers that look like a knight's chainmail and deep metallic indigo-blue body plumage, living on the slopes of the active Karthala volcano.",
    habitat: "Moist evergreen cloud forests on Grande Comore, Mohéli, and Anjouan",
    diet: "Frugivore - wild banyan figs and forest berries",
    endangered: "Vulnerable (Endemic)",
    predators: "Comoro harriers",
    funFact: "The silvery neck feathers have a distinct stiffened texture that the bird can raise into a protective collar when courting!",
    image: wikiImg("thumb/6/69/Alectroenas_sganzini_Keulemans.jpg/500px-Alectroenas_sganzini_Keulemans.jpg")
  },
  {
    country: "Congo (Brazzaville)",
    code: "CG",
    continent: "Africa",
    flag: "🇨🇬",
    name: "Hartlaub's Duck",
    scientific: "Pteronetta hartlaubii",
    tagline: "The chestnut river duck of Odzala National Park",
    description: "The iconic forest waterbird of the Republic of the Congo! A secretive, dark chestnut duck with striking sky-blue wing patches and a black head, paddling quietly along jungle streams beneath ancient mahogany trees.",
    habitat: "Dense equatorial rainforest rivers, swamps, and forest bais",
    diet: "Aquatic insects, water snails, small fish, and seeds",
    endangered: "Least Concern",
    predators: "Slender-snouted crocodiles and leopards",
    funFact: "Unlike northern ducks, Hartlaub's ducks frequently perch high in rainforest trees and nest inside hollow trunks 40 feet up!",
    image: wikiImg("thumb/b/b8/Pteronetta_hartlaubii_Keulemans.jpg/500px-Pteronetta_hartlaubii_Keulemans.jpg")
  },
  {
    country: "Djibouti",
    code: "DJ",
    continent: "Africa",
    flag: "🇩🇯",
    name: "Djibouti Francolin",
    scientific: "Pternistis ochropectus",
    tagline: "The critically endangered treasure of the Forêt du Day",
    description: "The national bird of Djibouti! Found only in the ancient juniper cloud forests of the Goda Mountains in Djibouti. A handsome gamebird with golden-ochre breast streaks and red bill, fighting for survival in its mountain sanctuary.",
    habitat: "Relict African juniper cloud forests of the Forêt du Day National Park",
    diet: "Juniper berries, termites, seeds, and wild fig shoots",
    endangered: "Critically Endangered (Endemic to Djibouti)",
    predators: "Caracals and servals",
    funFact: "The entire world population of the Djibouti Francolin lives in a tiny area of less than 6 square miles in the mountains!",
    image: wikiImg("thumb/2/23/Pternistis_ochropectus_Keulemans.jpg/500px-Pternistis_ochropectus_Keulemans.jpg")
  },
  {
    country: "Equatorial Guinea",
    code: "GQ",
    continent: "Africa",
    flag: "🇬🇶",
    name: "Black Crowned Crane",
    scientific: "Balearica pavonina",
    tagline: "The golden-crowned beauty of Monte Alén National Park",
    description: "The celebrated emblem of Equatorial Guinea's wetlands! Adorned with a magnificent fan of stiff golden feathers on its crown and white cheek patches flushed with red, it wades through lush coastal lagoons.",
    habitat: "Coastal river estuaries, freshwater swamps, and forest meadows",
    diet: "Seeds, marsh roots, frogs, and grasshoppers",
    endangered: "Vulnerable",
    predators: "Leopards and African rock pythons",
    funFact: "Equatorial Guinea's volcanic island of Bioko is also home to rare endemic subspecies of hornbills and sunbirds!",
    image: wikiImg("thumb/7/77/Balearica_pavonina_001.jpg/500px-Balearica_pavonina_001.jpg")
  },
  {
    country: "Eritrea",
    code: "ER",
    continent: "Africa",
    flag: "🇪🇷",
    name: "Abyssinian Ground Hornbill",
    scientific: "Bucorvus abyssinicus",
    tagline: "The giant turkey-sized predator of the Sahel",
    description: "The formidable savanna sentinel of Eritrea! Standing 3 feet tall with a heavy black bill and vivid red-and-blue bare facial wattles. It walks with a purposeful stride across the scrub, hunting venomous cobras with lethal precision.",
    habitat: "Savannah grasslands, semi-arid rocky hills, and acacia woods",
    diet: "Carnivore - venomous snakes, tortoises, scorpions, lizards, and rodents",
    endangered: "Vulnerable",
    predators: "Apex ground raptor (leopards on roosts)",
    funFact: "When hunting a venomous snake, ground hornbills hold their wings open like shields to block strikes while delivering fatal blows with their heavy bills!",
    image: wikiImg("thumb/3/30/Abyssinian_Ground_Hornbill_%28Bucorvus_abyssinicus%29.jpg/500px-Abyssinian_Ground_Hornbill_%28Bucorvus_abyssinicus%29.jpg")
  },
  {
    country: "Eswatini (Swaziland)",
    code: "SZ",
    continent: "Africa",
    flag: "🇸🇿",
    name: "Purple-Crested Turaco (Ligwalagwala)",
    scientific: "Gallirex porphyreolophus",
    tagline: "The royal feather bird of the Kingdom of Eswatini",
    description: "The national bird of the Kingdom of Eswatini! Known in SiSwati as 'Ligwalagwala.' Highly sacred in Swazi royalty, its brilliant crimson flight feathers are reserved exclusively for the King and royal family during traditional ceremonies.",
    habitat: "Riparian forests, evergreen bushveld, and montane ravines",
    diet: "Frugivore - wild figs, sycamore fruits, and podocarpus berries",
    endangered: "Least Concern",
    predators: "Crowned eagles and boomslang snakes",
    funFact: "In the famous annual Incwala national ceremony of Eswatini, the King wears the glowing scarlet wing feathers of this sacred bird!",
    image: wikiImg("thumb/8/8e/Purple-crested_turaco_%28Gallirex_porphyreolophus%29.jpg/500px-Purple-crested_turaco_%28Gallirex_porphyreolophus%29.jpg")
  },
  {
    country: "Gabon",
    code: "GA",
    continent: "Africa",
    flag: "🇬🇦",
    name: "African Grey Parrot (Ikosso)",
    scientific: "Psittacus erithacus",
    tagline: "The scarlet-tailed philosopher of Loango National Park",
    description: "The national bird of Gabon! Thriving in immense numbers across Gabon's 13 protected national parks. In Loango National Park ('Africa's Last Eden'), giant flocks fly between wild beaches, estuaries, and ancient equatorial canopies.",
    habitat: "Dense equatorial rainforests, coastal lagoons, and mangrove islands",
    diet: "Oil palm fruit, wild fig seeds, and tropical flowers",
    endangered: "Endangered",
    predators: "Crowned eagles",
    funFact: "Gabon contains the healthiest, most intact wild population of African Grey Parrots remaining anywhere in Africa!",
    image: wikiImg("thumb/7/73/Psittacus_erithacus_-perching_on_branch-8.jpg/500px-Psittacus_erithacus_-perching_on_branch-8.jpg")
  },
  {
    country: "Gambia",
    code: "GM",
    continent: "Africa",
    flag: "🇬🇲",
    name: "Abyssinian Roller",
    scientific: "Coracias abyssinicus",
    tagline: "The turquoise flash along the River Gambia",
    description: "The premier icon of The Gambia—internationally celebrated as a birdwatcher's paradise! Perched on roadside telephone wires and baobab branches, its luminous azure-blue wings flash as it plunges down for grasshoppers.",
    habitat: "River Gambia savannas, farmlands, and baobab groves",
    diet: "Grasshoppers, beetles, crickets, and small lizards",
    endangered: "Least Concern",
    predators: "Black kites",
    funFact: "Despite its small size, The Gambia is home to over 540 species of birds, making it one of the most bird-dense nations in the world!",
    image: wikiImg("thumb/1/14/Coracias_abyssinicus_Keulemans.jpg/500px-Coracias_abyssinicus_Keulemans.jpg")
  },
  {
    country: "Guinea",
    code: "GN",
    continent: "Africa",
    flag: "🇬🇳",
    name: "Black Crowned Crane",
    scientific: "Balearica pavonina",
    tagline: "The golden-crowned symbol of West African wetlands",
    description: "The national bird of Guinea! Honored on postage and cultural emblems. In the highlands of Fouta Djallon, where the Niger, Senegal, and Gambia rivers originate, its trumpeting calls ring through morning river mists.",
    habitat: "Fouta Djallon river basins, wet floodplains, and rice paddies",
    diet: "Seeds, grasshoppers, river snails, and tender tubers",
    endangered: "Vulnerable",
    predators: "Leopards and servals",
    funFact: "Its loud, resonant honk is produced by an extra-long coiled trachea that acts like a musical French horn inside its chest!",
    image: wikiImg("thumb/7/77/Balearica_pavonina_001.jpg/500px-Balearica_pavonina_001.jpg")
  },
  {
    country: "Guinea-Bissau",
    code: "GW",
    continent: "Africa",
    flag: "🇬🇼",
    name: "Western Reef Heron",
    scientific: "Egretta gularis",
    tagline: "The coral reef fisher of the Bijagós Archipelago",
    description: "The signature waterbird of Guinea-Bissau's UNESCO Bijagós Archipelago! Occurring in both charcoal-slate and pure white color phases, it stalks coral reefs and tidal flats, spreading its wings like an umbrella to spot fish.",
    habitat: "Bijagós Archipelago, mangrove mudflats, and Atlantic beaches",
    diet: "Carnivore - mudskippers, crabs, mullets, and small shrimp",
    endangered: "Least Concern",
    predators: "Ospreys and sharks (in water)",
    funFact: "They practice 'canopy feeding'—curving their wings forward into a shadow umbrella so fish swim toward the shade for safety, right into the heron's bill!",
    image: wikiImg("thumb/3/3a/Western_Reef_Heron_Egretta_gularis.jpg/500px-Western_Reef_Heron_Egretta_gularis.jpg")
  },
  {
    country: "Lesotho",
    code: "LS",
    continent: "Africa",
    flag: "🇱🇸",
    name: "Bearded Vulture (Lammergeier)",
    scientific: "Gypaetus barbatus",
    tagline: "The high-flying dragon of the Maloti-Drakensberg peaks",
    description: "The sovereign of Lesotho—the 'Kingdom in the Sky'! Lesotho is the only independent state in the world that lies entirely above 3,280 feet. Here, the Lammergeier rides fierce freezing updrafts over 11,000-foot basalt escarpments.",
    habitat: "High Maloti basalt crags, alpine plateaus, and snowbound gorges",
    diet: "Bones and bone marrow of sheep, goats, and mountain antelopes",
    endangered: "Near Threatened (Heavily Protected in Lesotho)",
    predators: "Apex mountain scavenger",
    funFact: "Basotho shepherds revere the Lammergeier as the master of mountain winds, capable of gliding safely through raging blizzards!",
    image: wikiImg("thumb/2/22/Gypaetus_barbatus_1_%28Marek_Szczepanek%29.jpg/500px-Gypaetus_barbatus_1_%28Marek_Szczepanek%29.jpg")
  },
  {
    country: "Liberia",
    code: "LR",
    continent: "Africa",
    flag: "🇱🇷",
    name: "Pepperbird (Common Bulbul)",
    scientific: "Pycnonotus barbatus",
    tagline: "The musical early-morning alarm of Liberia",
    description: "The national bird of Liberia! Known affectionately in Liberian English as the 'Pepperbird.' Famous in Liberian folklore as the punctual songster whose cheerful bubbling song awakens town and country before sunrise every day.",
    habitat: "Sapo National Park fringes, coastal gardens, and secondary forests",
    diet: "Omnivore - wild chili peppers, papayas, berries, and termites",
    endangered: "Least Concern",
    predators: "Gabar goshawks and house cats",
    funFact: "Liberia's premier national cultural magazine and national tourist programs are named 'The Pepperbird' in its honor!",
    image: wikiImg("thumb/3/3a/Common_bulbul_%28Pycnonotus_barbatus%29.jpg/500px-Common_bulbul_%28Pycnonotus_barbatus%29.jpg")
  },
  {
    country: "Libya",
    code: "LY",
    continent: "Africa",
    flag: "🇱🇾",
    name: "Houbara Bustard",
    scientific: "Chlamydotis undulata",
    tagline: "The camouflage master of the Sahara sand seas",
    description: "The national bird of Libya! A magnificent desert bird with sand-colored plumage that renders it virtually invisible against the Sahara dunes. Males display stunning black-and-white neck ruffs during courtship dances.",
    habitat: "Saharan gravel plains, desert wadis, and semi-arid plateaus",
    diet: "Desert beetles, grasshoppers, seeds, and wild desert melon shoots",
    endangered: "Vulnerable",
    predators: "Fennec foxes, caracals, and golden eagles",
    funFact: "If attacked by a falcon, the Houbara bustard can shoot a sticky, foul-smelling defensive liquid that glues the predator's flight feathers together!",
    image: wikiImg("thumb/0/07/Chlamydotis_undulata_Keulemans.jpg/500px-Chlamydotis_undulata_Keulemans.jpg")
  },
  {
    country: "Malawi",
    code: "MW",
    continent: "Africa",
    flag: "🇲🇼",
    name: "African Fish Eagle",
    scientific: "Haliaeetus vocifer",
    tagline: "The soaring fisherman of Lake Malawi (The Lake of Stars)",
    description: "The national bird of Malawi! Ruling the crystal-clear waters of Lake Malawi, home to over 1,000 species of colorful cichlid fish. Its ringing yodel echoes between the golden beaches and granite mountain headlands.",
    habitat: "Lake Malawi National Park, Shire River, and Lake Malombe",
    diet: "Lake Malawi cichlids, catfish, and freshwater crabs",
    endangered: "Least Concern",
    predators: "Apex aquatic raptor",
    funFact: "Lake Malawi contains more fish species than any other lake in the world, providing fish eagles with an endless buffet!",
    image: wikiImg("thumb/8/87/African_Fish_Eagle_%28Haliaeetus_vocifer%29.jpg/500px-African_Fish_Eagle_%28Haliaeetus_vocifer%29.jpg")
  },
  {
    country: "Mali",
    code: "ML",
    continent: "Africa",
    flag: "🇲🇱",
    name: "Mali Firefinch",
    scientific: "Lagonosticta virata",
    tagline: "The crimson rocky singer of the Bandiagara Escarpment",
    description: "The national bird of Mali! Endemic to the striking sandstone cliffs of the Dogon Country and Bandiagara Escarpment. The male is bathed in rich crimson-pink plumage, darting between ancient cliffside mud granaries.",
    habitat: "Bandiagara sandstone cliffs, rocky screes, and Sahelian ravines",
    diet: "Grass seeds, millet grains, and small termites",
    endangered: "Least Concern (Endemic to Mali/Senegal)",
    predators: "Rock kestrels",
    funFact: "The Dogon people of Mali honor this bird in traditional cliffside carvings representing joy and family fidelity!",
    image: wikiImg("thumb/9/94/Lagonosticta_senegala_male_Senegal.jpg/500px-Lagonosticta_senegala_male_Senegal.jpg")
  },
  {
    country: "Mauritania",
    code: "MR",
    continent: "Africa",
    flag: "🇲🇷",
    name: "Eurasian Spoonbill",
    scientific: "Platalea leucorodia",
    tagline: "The spatula-billed colonizer of the Banc d'Arguin",
    description: "The signature bird of Mauritania's Banc d'Arguin National Park! Mauritania hosts the world's most significant wintering wetland for over two million migratory waterbirds. Thousands of spoonbills nest on wind-sculpted sandbar islands.",
    habitat: "Banc d'Arguin UNESCO reserve, tidal mudflats, and sand islands",
    diet: "Shrimp, small marine fish, crabs, and aquatic worms",
    endangered: "Least Concern",
    predators: "Golden jackals",
    funFact: "Mauritania's Banc d'Arguin is so rich in fish that traditional Imraguen fishermen whistle to wild dolphins to help drive fish into their nets!",
    image: wikiImg("thumb/a/ad/African_spoonbill_%28Platalea_alba%29.jpg/500px-African_spoonbill_%28Platalea_alba%29.jpg")
  },
  {
    country: "Mozambique",
    code: "MZ",
    continent: "Africa",
    flag: "🇲🇿",
    name: "African Fish Eagle",
    scientific: "Haliaeetus vocifer",
    tagline: "The coastal sovereign of the Bazaruto Archipelago",
    description: "The national bird of Mozambique! Flocks patrol the turquoise waters of the Bazaruto coral islands and the wild floodplains of Gorongosa National Park, diving for tigerfish and marine mullet.",
    habitat: "Bazaruto Archipelago, Zambezi Delta, and Gorongosa Lake Urema",
    diet: "Fish, water monitors, and marine mullet",
    endangered: "Least Concern",
    predators: "Apex river raptor",
    funFact: "Gorongosa National Park in Mozambique has undergone one of the greatest wildlife restorations on Earth, with bird populations soaring!",
    image: wikiImg("thumb/8/87/African_Fish_Eagle_%28Haliaeetus_vocifer%29.jpg/500px-African_Fish_Eagle_%28Haliaeetus_vocifer%29.jpg")
  },
  {
    country: "Niger",
    code: "NE",
    continent: "Africa",
    flag: "🇳🇪",
    name: "Ostrich (Damacheq)",
    scientific: "Struthio camelus camelus",
    tagline: "The running legend of the Aïr and Ténéré desert reserves",
    description: "The proud symbol of Niger's vast Sahara expanses! Protected inside the immense Aïr and Ténéré Natural Reserves (the largest protected area in Africa), roaming alongside Tuareg nomads through sand dunes and mountain gorges.",
    habitat: "Aïr Mountains, Ténéré Desert dunes, and acacia plains",
    diet: "Desert seeds, wild gourds, thorny acacia shoots, and insects",
    endangered: "Critically Endangered",
    predators: "Saharan cheetahs and striped hyenas",
    funFact: "Ostriches don't actually bury their heads in the sand—they lay their long necks flat against the desert ground to look like a mound of dirt from a distance!",
    image: wikiImg("thumb/e/ed/Struthio_camelus_camelus_male.jpg/500px-Struthio_camelus_camelus_male.jpg")
  },
  {
    country: "Sao Tome and Principe",
    code: "ST",
    continent: "Africa",
    flag: "🇸🇹",
    name: "São Tomé Ibis (Bostrychia bocagei)",
    scientific: "Bostrychia bocagei",
    tagline: "The critically endangered dwarf ibis of ancient volcanic peaks",
    description: "The national bird of São Tomé and Príncipe! Endemic to the mist-shrouded primary rainforests around the colossal volcanic plug of Pico Cão Grande. It is the smallest ibis in the world, foraging quietly in pristine mossy valleys.",
    habitat: "Primary montane rainforests of Obô National Park on São Tomé",
    diet: "Invertebrates - earthworms, land snails, and beetle larvae",
    endangered: "Critically Endangered (Fewer than 150 survive)",
    predators: "Introduced feral pigs and mona monkeys",
    funFact: "São Tomé and Príncipe is known as the 'Galápagos of Africa' because of its extraordinary number of unique endemic bird species!",
    image: wikiImg("thumb/3/30/Bostrychia_bocagei_Keulemans.jpg/500px-Bostrychia_bocagei_Keulemans.jpg")
  },
  {
    country: "Sierra Leone",
    code: "SL",
    continent: "Africa",
    flag: "🇸🇱",
    name: "White-Necked Picathartes",
    scientific: "Picathartes gymnocephalus",
    tagline: "The ancient rockfowl of the Gola rainforest",
    description: "The flagship bird of Sierra Leone! Living deep within the ancient Gola Rainforest National Park. Its bald golden-yellow head and bounding, kangaroo-like hops make it one of the most remarkable avian sights on the African continent.",
    habitat: "Pristine rainforest boulder caves of the Gola Rainforest",
    diet: "Earthworms, beetles, forest crabs, and driver ants",
    endangered: "Vulnerable (Strictly Protected in Sierra Leone)",
    predators: "African rock pythons",
    funFact: "Sierra Leone's community conservation programs have trained local villagers as ecotourist guides to safeguard the bird's cave nesting sites!",
    image: wikiImg("thumb/5/5a/Picathartes_gymnocephalus_1.jpg/500px-Picathartes_gymnocephalus_1.jpg")
  },
  {
    country: "Somalia",
    code: "SO",
    continent: "Africa",
    flag: "🇸🇴",
    name: "Somali Thrush (Shimbir)",
    scientific: "Turdus ludoviciae",
    tagline: "The rare mountain singer of the ancient frankincense highlands",
    description: "The national bird of Somalia! Endemic to the mist-covered juniper mountain forests of the Cal Madow range in northern Somalia, where ancient frankincense and myrrh trees grow along dramatic limestone cliffs.",
    habitat: "African juniper forests of Cal Madow and Mount Shimbiris (Somalia's highest peak)",
    diet: "Juniper berries, wild figs, caterpillars, and beetles",
    endangered: "Critically Endangered (Endemic to Somalia)",
    predators: "Leopards and raptors",
    funFact: "Mount Shimbiris, the highest peak in Somalia (over 8,000 feet), was named directly after the Somali word for bird ('Shimbir')!",
    image: wikiImg("thumb/2/23/Turdus_ludoviciae_Keulemans.jpg/500px-Turdus_ludoviciae_Keulemans.jpg")
  },
  {
    country: "South Sudan",
    code: "SS",
    continent: "Africa",
    flag: "🇸🇸",
    name: "Shoebill (Abu Markub)",
    scientific: "Balaeniceps rex",
    tagline: "The giant dinosaur bird with the Dutch-clog shoe bill",
    description: "The national bird of South Sudan! Dominating the vast papyrus swamps of the Sudd (the largest freshwater wetland in Africa). Standing 5 feet tall with a massive shoe-shaped bill, it stands motionless for hours before striking like lightning.",
    habitat: "The Sudd papyrus swamps and floating vegetation beds",
    diet: "Carnivore - giant lungfish, bichirs, catfish, and baby crocodiles",
    endangered: "Vulnerable",
    predators: "Large Nile crocodiles",
    funFact: "A Shoebill can stand completely frozen without blinking for up to 30 minutes, waiting for a giant lungfish to surface for air!",
    image: wikiImg("thumb/8/82/Shoebill_Balaeniceps_rex.jpg/500px-Shoebill_Balaeniceps_rex.jpg")
  },
  {
    country: "Sudan",
    code: "SD",
    continent: "Africa",
    flag: "🇸🇩",
    name: "Secretarybird (Saqr el-Gidyān)",
    scientific: "Sagittarius serpentarius",
    tagline: "The snake-stomping raptor on the national emblem of Sudan",
    description: "The proud national emblem of the Republic of Sudan! A magnificent raptor on long crane-like legs with black quill-like crest feathers behind its head. It hunts on foot, stomping venomous cobras with 40 pounds of kick force!",
    habitat: "Nile savannas, open thorn scrub, and semi-arid grasslands",
    diet: "Carnivore - puff adders, cobras, lizards, locusts, and rodents",
    endangered: "Endangered",
    predators: "Apex raptor (cheetahs occasionally contest catches)",
    funFact: "A Secretarybird's kick strikes in just 15 milliseconds—faster than the blink of a human eye!",
    image: wikiImg("thumb/0/07/Secretary_bird_%28Sagittarius_serpentarius%29.jpg/500px-Secretary_bird_%28Sagittarius_serpentarius%29.jpg")
  },
  {
    country: "Togo",
    code: "TG",
    continent: "Africa",
    flag: "🇹🇬",
    name: "Red-Necked Buzzard",
    scientific: "Buteo auguralis",
    tagline: "The red-tailed hunter of the Mount Agou hills",
    description: "The iconic bird of prey of Togo! Featuring rich rufous-chestnut neck hackles and a dark brown mantle, it soars over the coffee plantations and tropical hills surrounding Mount Agou (Togo's highest peak).",
    habitat: "Forest edges, mountain hillsides, and tropical wooded savannas",
    diet: "Lizards, tree frogs, beetles, grasshoppers, and field mice",
    endangered: "Least Concern",
    predators: "Apex aerial raptor",
    funFact: "These buzzards often perch high on palm fronds to watch for lizards scurrying across sun-warmed cocoa beans drying in villages!",
    image: wikiImg("thumb/8/87/Buteo_auguralis_Keulemans.jpg/500px-Buteo_auguralis_Keulemans.jpg")
  },
  {
    country: "Tunisia",
    code: "TN",
    continent: "Africa",
    flag: "🇹🇳",
    name: "Greater Flamingo",
    scientific: "Phoenicopterus roseus",
    tagline: "The coral-pink legions of Lake Ichkeul",
    description: "The national bird of Tunisia! Tens of thousands of these majestic birds winter at UNESCO Lake Ichkeul and coastal salt lakes ('chotts') near Tunis, creating an unforgettable sea of shimmering pink against blue Mediterranean skies.",
    habitat: "Lake Ichkeul UNESCO reserve, coastal lagoons, and Chott el Djerid",
    diet: "Filter feeder - brine shrimp, diatoms, and aquatic insects",
    endangered: "Least Concern",
    predators: "Golden jackals (on shallow edges)",
    funFact: "Flamingos can sleep soundly while balanced on just one leg to reduce heat loss through their unfeathered feet!",
    image: wikiImg("thumb/9/94/Flamingos_Laguna_Colorada.jpg/500px-Flamingos_Laguna_Colorada.jpg")
  },

  // --- OCEANIA (FINAL NATIONS) ---
  {
    country: "Nauru",
    code: "NR",
    continent: "Oceania",
    flag: "🇳🇷",
    name: "Nauru Reed Warbler (Itsirir)",
    scientific: "Acrocephalus rehsei",
    tagline: "The only endemic land bird on the island of Nauru",
    description: "The official national bird of Nauru! Known locally as 'Itsirir.' The only endemic land bird species on the entire island nation. It has a cheerful warbling song that rings out across coconut palms and tropical hibiscus gardens.",
    habitat: "Limestone pinnacles, central plateau scrub, and coastal gardens",
    diet: "Insectivore - dragonflies, moths, beetles, and spiders",
    endangered: "Vulnerable (Endemic to Nauru)",
    predators: "Invasive feral cats",
    funFact: "Its whistling melody is celebrated on Nauru postage and national heritage coins!",
    image: wikiImg("thumb/5/5a/Acrocephalus_rehsei_Keulemans.jpg/500px-Acrocephalus_rehsei_Keulemans.jpg")
  },
  {
    country: "Tuvalu",
    code: "TV",
    continent: "Oceania",
    flag: "🇹🇻",
    name: "Black Noddy (Lakia)",
    scientific: "Anous minutus",
    tagline: "The jet-black wave dancer of Funafuti Lagoon",
    description: "The beloved cultural bird of Tuvalu! Known in Tuvaluan as 'Lakia.' A handsome dark charcoal tern with a gleaming snowy white cap. Thousands nest in puka trees on the remote islets of the Funafuti Conservation Area.",
    habitat: "Funafuti atoll islets, coconut groves, and open Pacific waters",
    diet: "Small flying fish, anchovies, and marine surface squid",
    endangered: "Least Concern",
    predators: "Frigatebirds",
    funFact: "Tuvaluan fishermen historically used flocks of Lakia to pinpoint large schools of tuna swimming beneath the waves!",
    image: wikiImg("thumb/3/30/Anous_minutus_-Lord_Howe_Island-8.jpg/500px-Anous_minutus_-Lord_Howe_Island-8.jpg")
  }
];

// Combine all countries
const ALL_COUNTRIES = [
  ...COUNTRY_BIRDS_RAW,
  ...MORE_COUNTRIES_RAW,
  ...FINAL_COUNTRIES_RAW,
  ...REMAINING_NATIONS
];

// Deduplicate by country name if any
const countryMap = new Map();
ALL_COUNTRIES.forEach(c => {
  if (!countryMap.has(c.country)) {
    countryMap.set(c.country, c);
  }
});

const FINAL_COUNTRY_LIST = Array.from(countryMap.values());
FINAL_COUNTRY_LIST.sort((a, b) => a.country.localeCompare(b.country));

console.log("Total unique countries compiled:", FINAL_COUNTRY_LIST.length);
console.log("Total US states compiled:", US_STATE_BIRDS_RAW.length);

// Format into output JS
const outputContent = `// WORLD BIRD ATLAS & GEOGRAPHIC DATABASE
// Covers ALL 50 US States (+ DC, PR, GU) and 195+ Countries of the World!
if (typeof window === 'undefined') { var window = global; }

window.US_STATE_BIRDS = ${JSON.stringify(US_STATE_BIRDS_RAW.map((s, idx) => ({
  id: "state-bird-" + s.code.toLowerCase(),
  name: s.name,
  scientific: s.scientific,
  category: "birds",
  geographicType: "us_state",
  jurisdiction: s.state,
  stateCode: s.code,
  flagEmoji: s.flag,
  badgeText: s.flag + " " + s.state + " State Bird",
  tagline: s.tagline,
  description: s.description,
  habitat: s.habitat,
  diet: s.diet,
  endangered: s.endangered,
  predators: s.predators,
  funFact: s.funFact,
  image: s.image,
  emoji: "🦅"
})), null, 2)};

window.WORLD_COUNTRY_BIRDS = ${JSON.stringify(FINAL_COUNTRY_LIST.map((c, idx) => ({
  id: "country-bird-" + (c.code ? c.code.toLowerCase() : "c" + idx),
  name: c.name,
  scientific: c.scientific,
  category: "birds",
  geographicType: "country",
  jurisdiction: c.country,
  countryCode: c.code,
  continent: c.continent,
  flagEmoji: c.flag,
  badgeText: c.flag + " " + c.country + " National Bird",
  tagline: c.tagline,
  description: c.description,
  habitat: c.habitat,
  diet: c.diet,
  endangered: c.endangered,
  predators: c.predators,
  funFact: c.funFact,
  image: c.image,
  emoji: "🦜"
})), null, 2)};

console.log("Loaded Geographic Birds:", window.US_STATE_BIRDS.length, "US States &", window.WORLD_COUNTRY_BIRDS.length, "Countries");
`;

fs.writeFileSync(path.join(__dirname, '../data/birds_geographic.js'), outputContent, 'utf8');
console.log("Successfully wrote data/birds_geographic.js!");
